import Link from 'next/link';
import { getSupabaseAdmin } from '@/lib/supabase/server';

const items:Array<[string,string]>=[['Journey Requests','/admin/requests'],['Bookings','/admin/bookings'],['Groups','/admin/groups'],['Guests','/admin/guests'],['Operations','/admin/operations'],['Hosts','/admin/hosts'],['Hotels','/admin/hotels'],['Transportation','/admin/transportation'],['Train','/admin/train'],['Payments','/admin/payments'],['Expenses','/admin/expenses'],['Reviews','/admin/reviews'],['Communications','/admin/communications'],['Reports','/admin/reports'],['Settings','/admin/settings']];
type PaymentRow={amount:number|string;status:string};
export default async function AdminHome(){
 let stats={requests:0,pending:0,confirmed:0,active:0,revenue:0,pendingPayments:0}; let setup=false;
 try{const s=getSupabaseAdmin(); const [r,p,c,a,pay]=await Promise.all([s.from('journey_requests').select('*',{count:'exact',head:true}),s.from('bookings').select('*',{count:'exact',head:true}).eq('payment_status','PAYMENT_PENDING'),s.from('bookings').select('*',{count:'exact',head:true}).eq('status','CONFIRMED'),s.from('bookings').select('*',{count:'exact',head:true}).eq('status','ACTIVE'),s.from('payments').select('amount,status')]); stats.requests=r.count||0;stats.pending=p.count||0;stats.confirmed=c.count||0;stats.active=a.count||0;stats.revenue=((pay.data||[]) as PaymentRow[]).filter(x=>x.status==='RECEIVED').reduce((n,x)=>n+Number(x.amount),0);stats.pendingPayments=((pay.data||[]) as PaymentRow[]).filter(x=>x.status==='PENDING_VERIFICATION').reduce((n,x)=>n+Number(x.amount),0);}catch{setup=true}
 return <section className="section"><div className="container"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="eyebrow">Alharamainelite</div><h1 className="serif mt-3 text-5xl text-forest">Operations dashboard.</h1><p className="mt-3 text-forest/55">A working control centre for journeys, guests and operations.</p></div><Link href="/" className="btn btn-outline">View website</Link></div>{setup&&<div className="mt-8 border border-gold/40 bg-[#fffaf0] p-5 text-sm leading-6 text-forest/70"><b className="text-forest">Supabase setup required.</b> Add the production environment variables and apply the migration before live dashboard data can load.</div>}<div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['New Requests',stats.requests],['Payment Pending',stats.pending],['Confirmed',stats.confirmed],['Active Journeys',stats.active]].map(([a,b])=><div className="card p-6" key={a as string}><div className="eyebrow">{a as string}</div><div className="serif mt-3 text-4xl text-forest">{b as number}</div></div>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="card p-6"><div className="eyebrow">Payments received</div><div className="serif mt-3 text-4xl text-forest">${stats.revenue.toLocaleString()}</div></div><div className="card p-6"><div className="eyebrow">Pending verification</div><div className="serif mt-3 text-4xl text-forest">${stats.pendingPayments.toLocaleString()}</div></div></div><div className="mt-10"><div className="eyebrow">Workspace</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(([name,href])=><Link key={href} href={href} className="card p-5 transition hover:-translate-y-0.5 hover:border-gold/60"><div className="font-semibold text-forest">{name}</div><div className="mt-1 text-sm text-forest/45">Open workspace</div></Link>)}</div></div></div></section>}
