import Link from 'next/link';
import {cookies} from 'next/headers';
import {defaultLocale,isLocale} from '@/lib/i18n';
import {ArrowRight,Check,Heart,ShieldCheck,Users} from 'lucide-react';

const copy={
 en:{eyebrow:"WOMEN’S UMRAH · A PRIVATE, CONSIDERED EXPERIENCE",title:"A more comfortable way to make Umrah — designed around women.",intro:"From the first conversation to the final day, your journey is planned with clarity, privacy and thoughtful support. Choose the Signature or Elite journey, then tell us what you need. Your request is automatically marked as Women’s Umrah for our team.",promiseTitle:"Thoughtful support. Clear choices. No guesswork.",promiseText:"The Women’s Umrah section uses the same transparent Signature and Elite pricing as our main journeys. What changes is the way our team handles your request: with the women’s journey context visible from the moment it reaches our system.",signatureTitle:"SIGNATURE",signatureDesc:"A refined 10-day journey with premium accommodation, breakfast, private transportation, ziyarat, Jeddah experience, travel SIM and journey support.",eliteTitle:"ELITE",eliteDesc:"A higher-comfort 10-day journey with luxury accommodation, breakfast, Haramain Train economy where applicable, private transportation, ziyarat, Jeddah experience, travel SIM and journey support.",perGuest:"per guest · 10 days / 9 nights",choose:"Choose Signature",chooseElite:"Choose Elite",includedTitle:"Included within your journey",included:["Premium accommodation selected for your journey level","Private transportation throughout the confirmed itinerary","Makkah, Madinah and Jeddah experiences","Ziyarat and coordinated journey support","Travel SIM / connectivity support"],supportTitle:"Your Women’s Umrah request is clearly identified",supportText:"Our sales and operations teams see a Women’s Umrah marker on the request, booking and operational workflow. Any specific preferences are discussed and confirmed with you before the itinerary is finalized.",note:"Flights are not included at launch. Your expected travel period is collected first, then the final itinerary is coordinated with you."},
 so:{eyebrow:"CUMRADA HAWEENKA · KHIBRAD SI FIICAN LOO QORSHEEYEY",title:"Hab raaxo badan oo Cumrada loo guto — oo haweenka loogu qorsheeyay.",intro:"Laga bilaabo wada hadalka koowaad ilaa maalinta ugu dambaysa, safarka waxaa loo qorsheeyaa si cad, asturan oo taageero leh. Dooro Signature ama Elite, kadibna noo sheeg waxa aad u baahan tahay. Codsigaaga si toos ah waxaa loogu calaamadeeyaa Cumrada Haweenka.",promiseTitle:"Taageero la tixgeliyey. Doorasho cad. Jahawareer la’aan.",promiseText:"Qaybta Cumrada Haweenka waxay isticmaashaa qiimaha cad ee Signature iyo Elite. Waxa gaar ah waa in kooxdaadu aragto in codsigu ka yimid qaybta haweenka laga bilaabo nidaamka ilaa hawlgalka.",signatureTitle:"SIGNATURE",signatureDesc:"Safar 10 maalmood ah oo leh hoy heer sare ah, quraac, gaadiid gaar ah, ziyaraat, khibradda Jeddah, SIM iyo taageerada safarka.",eliteTitle:"ELITE",eliteDesc:"Safar 10 maalmood ah oo raaxo dheeraad ah leh, hoy luxury ah, quraac, Haramain Train economy marka uu ku habboon yahay, gaadiid gaar ah, ziyaraat, Jeddah, SIM iyo taageero.",perGuest:"qofkiiba · 10 maalmood / 9 habeen",choose:"Dooro Signature",chooseElite:"Dooro Elite",includedTitle:"Waxyaabaha ku jira safarka",included:["Hoy heerkiisa ku habboon oo si taxaddar leh loo doortay","Gaadiid gaar ah inta lagu jiro barnaamijka la xaqiijiyay","Khibradaha Makkah, Madiinah iyo Jeddah","Ziyaaro iyo taageero safar oo isku dubbaridan","SIM safar iyo taageero isku xirnaanta"],supportTitle:"Codsigaaga Cumrada Haweenka si cad ayaa loo aqoonsanayaa",supportText:"Kooxaha iibka iyo hawlgalku waxay arkaan calaamadda Cumrada Haweenka ee codsiga, booking-ka iyo hawlaha. Baahiyaha gaarka ah waxaa lagula xaqiijinayaa ka hor jadwalka kama dambaysta ah.",note:"Duulimaadyadu kuma jiraan bilowga. Waxaan marka hore ururinaynaa muddada safarka aad filayso, kadibna si wadajir ah ayaan u qorshaynaynaa faahfaahinta."},
 ar:{eyebrow:"عمرة النساء · تجربة هادئة ومدروسة",title:"عمرة أكثر راحة وخصوصية — صُممت لتناسب احتياجات النساء.",intro:"من أول تواصل وحتى اليوم الأخير، نخطط لرحلتك بوضوح وخصوصية واهتمام بالتفاصيل. اختاري SIGNATURE أو ELITE، ثم أخبرينا بما تحتاجينه. وسيظهر طلبك تلقائيًا في نظامنا على أنه قادم من قسم عمرة النساء.",promiseTitle:"دعم مدروس. خيارات واضحة. بلا تعقيد.",promiseText:"قسم عمرة النساء يستخدم نفس أسعار SIGNATURE وELITE الواضحة الموجودة في رحلاتنا الأساسية. ما يميّز المسار هو أن فريق المبيعات والعمليات يرى سياق عمرة النساء منذ وصول الطلب إلى النظام وحتى التنفيذ.",signatureTitle:"SIGNATURE",signatureDesc:"رحلة متكاملة لمدة 10 أيام تشمل إقامة راقية، إفطارًا، تنقلات خاصة، زيارات، تجربة جدة، شريحة سفر ودعمًا مستمرًا للرحلة.",eliteTitle:"ELITE",eliteDesc:"مستوى أعلى من الراحة لمدة 10 أيام مع إقامة فاخرة، إفطار، قطار الحرمين الاقتصادي عند ملاءمته للبرنامج، تنقلات خاصة، زيارات، تجربة جدة، شريحة سفر ودعم الرحلة.",perGuest:"للضيف · 10 أيام / 9 ليالٍ",choose:"اختاري SIGNATURE",chooseElite:"اختاري ELITE",includedTitle:"ما يتضمنه برنامج الرحلة",included:["إقامة راقية يتم اختيارها وفق مستوى الرحلة","تنقلات خاصة ضمن البرنامج المؤكد","تجارب مكة والمدينة وجدة","الزيارات ودعم الرحلة والتنسيق","شريحة سفر ودعم الاتصال"],supportTitle:"طلبك من قسم عمرة النساء ظاهر بوضوح لفريقنا",supportText:"يرى فريقا المبيعات والعمليات علامة «عمرة النساء» على الطلب والحجز وسير العمل التشغيلي. وأي تفضيلات أو ترتيبات خاصة يتم مناقشتها وتأكيدها معك قبل اعتماد البرنامج النهائي.",note:"الرحلات الجوية غير مشمولة عند الإطلاق. نجمع أولًا الفترة المتوقعة للسفر، ثم ننسق معك التفاصيل النهائية للرحلة."}
} as const;

export default async function Womens(){
 const raw=(await cookies()).get('he_locale')?.value; const locale=isLocale(raw)?raw:defaultLocale; const t=copy[locale];
 const cards=[{name:"SIGNATURE",price:"$2,000",title:t.signatureTitle,desc:t.signatureDesc,href:"/request-journey?package=signature&source=womens-umrah"},{name:"ELITE",price:"$2,500",title:t.eliteTitle,desc:t.eliteDesc,href:"/request-journey?package=elite&source=womens-umrah"}];
 return <section className="section overflow-hidden"><div className="container max-w-6xl">
  <div className="relative overflow-hidden rounded-[36px] border border-gold/20 bg-[#063f35] px-7 py-12 text-white shadow-[0_30px_100px_rgba(6,63,53,.18)] md:px-12 md:py-16">
   <div className="absolute -right-24 -top-24 h-72 w-72 rounded-full border border-gold/20 bg-gold/5"/><div className="absolute -bottom-32 -left-20 h-80 w-80 rounded-full border border-white/10"/>
   <div className="relative max-w-4xl"><div className="flex items-center gap-3 text-xs font-semibold tracking-[.18em] text-[#e1c75b]"><Heart size={16}/>{t.eyebrow}</div><h1 className="serif mt-5 text-4xl leading-[1.15] md:text-6xl">{t.title}</h1><p className="mt-6 max-w-3xl text-base leading-8 text-white/75 md:text-lg">{t.intro}</p>
   <div className="mt-8 flex flex-wrap gap-3">{t.included.slice(0,3).map(x=><div key={x} className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/80"><ShieldCheck size={15} className="text-[#e1c75b]"/>{x}</div>)}</div></div>
  </div>
  <div className="mt-12 grid gap-6 lg:grid-cols-[1fr_.72fr]"><div><div className="eyebrow">{t.promiseTitle}</div><h2 className="serif mt-3 text-4xl text-forest md:text-5xl">{t.promiseTitle}</h2><p className="mt-5 max-w-2xl text-base leading-8 text-forest/60">{t.promiseText}</p><div className="mt-7 rounded-2xl border border-gold/20 bg-[#f7f3ea] p-5 text-sm leading-7 text-forest/70">{t.note}</div></div>
   <div className="rounded-[28px] border border-forest/10 bg-white p-7 shadow-[0_20px_70px_rgba(6,63,53,.07)]"><div className="eyebrow">{t.includedTitle}</div><ul className="mt-5 space-y-4">{t.included.map(x=><li key={x} className="flex gap-3 text-sm leading-6 text-forest/70"><span className="mt-1 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#f7f3ea]"><Check size={13} className="text-gold"/></span>{x}</li>)}</ul></div>
  </div>
  <div className="mt-14 grid gap-6 lg:grid-cols-2">{cards.map((p,i)=><article key={p.name} className={'relative overflow-hidden rounded-[30px] border p-7 md:p-9 '+(i===1?'border-gold/35 bg-[#fbfaf6]':'border-forest/10 bg-white')}><div className="absolute right-0 top-0 h-24 w-24 rounded-bl-[60px] bg-[#f7f3ea]"/><div className="relative flex items-start justify-between gap-4"><div><div className="eyebrow">{p.name}</div><h2 className="serif mt-3 text-3xl text-forest">{p.title}</h2></div><Heart size={22} className="text-gold"/></div><div className="relative mt-8 flex items-end justify-between gap-5"><div><div className="serif text-5xl text-forest">{p.price}</div><div className="mt-1 text-sm text-forest/45">{t.perGuest}</div></div><div className="hidden rounded-full border border-gold/25 px-3 py-1 text-xs font-semibold text-forest sm:block">{i===1?(locale==='ar'?'راحة أعلى':locale==='so'?'Raaxo dheeraad ah':'Elevated comfort'):(locale==='ar'?'راحة راقية':locale==='so'?'Raaxo heer sare':'Refined comfort')}</div></div><p className="mt-6 min-h-[112px] text-sm leading-7 text-forest/65">{p.desc}</p><Link href={p.href} className="btn btn-primary mt-6 w-full">{i===1?t.chooseElite:t.choose}<ArrowRight size={16} className="ml-2"/></Link></article>)}</div>
  <div className="mt-10 rounded-[30px] border border-gold/25 bg-[#f7f3ea] p-7 md:p-9"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="eyebrow">{t.supportTitle}</div><h2 className="serif mt-3 text-3xl text-forest">{t.supportTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-forest/65">{t.supportText}</p></div><div className="shrink-0 rounded-2xl bg-white p-4"><Users className="text-gold" size={28}/></div></div></div>
 </div></section>;
}
