import Link from 'next/link';
import {cookies} from 'next/headers';
import {defaultLocale,isLocale} from '@/lib/i18n';
import {ArrowRight,Heart,ShieldCheck,Users} from 'lucide-react';

const copy={
  en:{eyebrow:"Women’s Umrah",title:"A WOMEN’S UMRAH JOURNEY, WITH THE SAME CLEAR CHOICE.",intro:"Choose the same Signature or Elite journey, with your request clearly marked as coming from the Women’s Umrah section so our team can coordinate the appropriate support.",note:"The package, pricing, duration and core booking flow remain the same.",signatureTitle:"Comfortable & meaningful",signatureDesc:"Premium hotels, breakfast, private transportation, ziyarat, Jeddah experience, SIM and journey support.",eliteTitle:"A higher level of comfort",eliteDesc:"Luxury accommodation, breakfast, Haramain Train economy where applicable, private transportation, ziyarat, Jeddah experience, SIM and journey support.",perGuest:"per guest · 10 days / 9 nights",choose:"Choose Signature",chooseElite:"Choose Elite",supportTitle:"Women’s journey support",supportText:"Your request is tagged as Women’s Umrah in our booking system. Any specific support or arrangements are confirmed with you before the itinerary is finalized.",points:["Clear package pricing","Small-group planning","Personal communication"]},
  so:{eyebrow:"Cumrada Haweenka",title:"SAFAR CUMRO OO HAWEEN AH, OO LEH DOORASHO CAD.",intro:"Dooro isla safarka Signature ama Elite, codsigaagana si cad ayaa loogu calaamadeynayaa inuu ka yimid qaybta Cumrada Haweenka si kooxdayadu u qorsheyso taageerada ku habboon.",note:"Xirmada, qiimaha, muddada iyo habka codsiga aasaasiga ah waa isku mid.",signatureTitle:"Raaxo & macne",signatureDesc:"Hoteello heer sare ah, quraac, gaadiid gaar ah, ziyaraat, khibradda Jeddah, SIM iyo taageero safar.",eliteTitle:"Heer raaxo oo sarreeya",eliteDesc:"Hoy luxury ah, quraac, Haramain Train economy marka uu ku habboon yahay, gaadiid gaar ah, ziyaraat, khibradda Jeddah, SIM iyo taageero safar.",perGuest:"qofkiiba · 10 maalmood / 9 habeen",choose:"Dooro Signature",chooseElite:"Dooro Elite",supportTitle:"Taageerada safarka haweenka",supportText:"Codsigaaga waxaa nidaamka lagu calaamadeynayaa Cumrada Haweenka. Taageero ama qabanqaabo gaar ah waxaa laguu xaqiijinayaa ka hor dhammeystirka jadwalka safarka.",points:["Qiime cad","Qorshe kooxo yaryar","Isgaarsiin qofeed"]},
  ar:{eyebrow:"عمرة النساء",title:"رحلة عمرة للنساء، بنفس الخيارات الواضحة.",intro:"اختاري باقة SIGNATURE أو ELITE نفسها، وسيتم تمييز طلبك بوضوح بأنه قادم من قسم عمرة النساء حتى ينسق فريقنا الدعم المناسب.",note:"الباقة والسعر والمدة وآلية الطلب الأساسية هي نفسها.",signatureTitle:"راحة ومعنى",signatureDesc:"فنادق راقية، إفطار، تنقلات خاصة، زيارات، تجربة جدة، شريحة إنترنت ودعم الرحلة.",eliteTitle:"مستوى أعلى من الراحة",eliteDesc:"إقامة فاخرة، إفطار، قطار الحرمين الاقتصادي حيث يناسب البرنامج، تنقلات خاصة، زيارات، تجربة جدة، شريحة إنترنت ودعم الرحلة.",perGuest:"للضيف · 10 أيام / 9 ليالٍ",choose:"اختاري SIGNATURE",chooseElite:"اختاري ELITE",supportTitle:"دعم رحلة النساء",supportText:"سيتم وسم طلبك في نظام الحجوزات بأنه من قسم عمرة النساء. يتم تأكيد أي دعم أو ترتيبات خاصة معك قبل اعتماد البرنامج النهائي.",points:["أسعار واضحة","تخطيط للمجموعات الصغيرة","تواصل شخصي"]}
} as const;

export default async function Womens(){
  const raw=(await cookies()).get('he_locale')?.value;
  const locale=isLocale(raw)?raw:defaultLocale;
  const t=copy[locale];
  const cards=[
    {name:"SIGNATURE",price:"$2,000",title:t.signatureTitle,desc:t.signatureDesc,href:"/request-journey?package=signature&source=womens-umrah"},
    {name:"ELITE",price:"$2,500",title:t.eliteTitle,desc:t.eliteDesc,href:"/request-journey?package=elite&source=womens-umrah"}
  ];
  const icons=[ShieldCheck,Users,Heart];
  return <section className="section"><div className="container max-w-6xl">
    <div className="max-w-4xl"><div className="eyebrow">{t.eyebrow}</div><h1 className="serif mt-4 text-5xl text-forest md:text-7xl">{t.title}</h1><p className="mt-6 text-lg leading-8 text-forest/65">{t.intro}</p><p className="mt-3 text-sm text-forest/50">{t.note}</p></div>
    <div className="mt-10 grid gap-6 lg:grid-cols-2">{cards.map(p=><article key={p.name} className="overflow-hidden rounded-[28px] border border-forest/10 bg-white p-7 shadow-[0_25px_80px_rgba(6,63,53,.08)]"><div className="flex items-center justify-between gap-4"><div className="eyebrow">{p.name}</div><Heart size={22} className="text-gold"/></div><h2 className="serif mt-3 text-3xl text-forest">{p.title}</h2><div className="serif mt-4 text-5xl text-forest">{p.price}</div><div className="mt-1 text-sm text-forest/45">{t.perGuest}</div><p className="mt-5 text-sm leading-7 text-forest/65">{p.desc}</p><Link href={p.href} className="btn btn-primary mt-7 w-full">{p.name==="ELITE"?t.chooseElite:t.choose}<ArrowRight size={16} className="ml-2"/></Link></article>)}</div>
    <div className="mt-10 grid gap-4 md:grid-cols-3">{t.points.map((point,i)=>{const Icon=icons[i];return <div key={point} className="card p-6"><div className="flex items-center gap-3"><span className="rounded-full bg-[#f7f3ea] p-2"><Icon size={19} className="text-gold"/></span><span className="font-semibold text-forest">{point}</span></div></div>})}</div>
    <div className="mt-10 rounded-[28px] border border-gold/30 bg-[#f7f3ea] p-7"><h2 className="serif text-3xl text-forest">{t.supportTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-forest/65">{t.supportText}</p></div>
  </div></section>;
}