import Link from 'next/link';
import {ArrowRight, ShieldCheck, Users, HeartHandshake, Hotel, TrainFront, Car, MapPinned} from 'lucide-react';
import {SectionHeading} from '@/components/ui/SectionHeading';
import {PriceCalculator} from '@/components/booking/PriceCalculator';
const hero='https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&w=1800&q=85';
const jeddah='https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1200&q=85';
export default function Home(){return <main>
<section className="relative min-h-[78vh] overflow-hidden bg-forest text-white"><img src={hero} alt="Makkah and the Kaaba" className="absolute inset-0 h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-r from-forest/95 via-forest/65 to-transparent"/><div className="container relative flex min-h-[78vh] items-center py-24"><div className="max-w-3xl"><div className="eyebrow">Premium Umrah Journeys</div><h1 className="serif mt-5 text-6xl leading-[.95] md:text-8xl">A JOURNEY WORTH REMEMBERING.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/80">Premium Umrah journeys thoughtfully designed for Somali Muslims around the world.</p><p className="mt-4 max-w-2xl text-sm leading-7 text-white/60">Small groups, carefully planned stays, private transportation and personal support throughout your journey.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/request-journey" className="btn bg-gold text-forest">Plan your journey</Link><Link href="/packages" className="btn border border-white/40 text-white">Explore our packages</Link></div></div></div></section>
<section className="border-b border-forest/10 bg-white py-6"><div className="container grid gap-5 text-sm text-forest/70 md:grid-cols-4">{[['Premium service',ShieldCheck],['Small groups',Users],['Personal support',HeartHandshake],['Thoughtful planning',MapPinned]].map(([x,I])=><div className="flex items-center gap-3" key={x as string}><I size={18} className="text-gold"/>{x as string}</div>)}</div></section>
<section className="section"><div className="container grid gap-12 md:grid-cols-2 md:items-center"><SectionHeading eyebrow="More than an Umrah trip" title="A JOURNEY DESIGNED AROUND YOU.">From your first request to your return home, we bring the important details together into one considered experience.</SectionHeading><div className="grid grid-cols-2 gap-4">{[['01','Comfort','Premium accommodation and practical arrangements.'],['02','Support','Personal assistance when you need it.'],['03','Small groups','A more personal and manageable group experience.'],['04','Connection','A service shaped with the Somali diaspora in mind.']].map(([n,t,d])=><div className="card p-6" key={n}><div className="eyebrow">{n}</div><h3 className="serif mt-3 text-2xl text-forest">{t}</h3><p className="mt-3 text-sm leading-6 text-forest/60">{d}</p></div>)}</div></div></section>
<section className="section bg-forest text-white"><div className="container"><SectionHeading eyebrow="Made for Somali travelers" title="A SERVICE DESIGNED WITH THE DIASPORA IN MIND." inverse><span className="text-white/70">For Somali Muslims living in the UK, United States, Canada, Europe, Australia and communities around the world. The experience is premium, culturally aware and built around clear communication.</span></SectionHeading></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Our Umrah packages" title="TWO WAYS TO JOURNEY.">Both packages are 10 days / 9 nights. International flights are not included. Prices are shown clearly per guest.</SectionHeading><div className="mt-10 grid gap-6 md:grid-cols-2">{[['SIGNATURE','$2,000','Premium hotels, breakfast, private transportation, ziyarat, Jeddah experience, SIM and journey support.','/packages/signature'],['ELITE','$2,500','Luxury accommodation, breakfast, Haramain Train economy class, private transportation, ziyarat, Jeddah experience, SIM and journey support.','/packages/elite']].map(([n,p,d,h],i)=><article className={`card p-8 ${i===1?'border-gold':''}`} key={n}><div className="eyebrow">{n}</div><div className="serif mt-4 text-5xl text-forest">{p}</div><p className="mt-2 text-sm text-forest/50">per guest · 10 days / 9 nights</p><p className="mt-7 leading-7 text-forest/70">{d}</p><Link href={h} className="btn btn-outline mt-8">View package <ArrowRight size={16} className="ml-2"/></Link></article>)}</div></div></section>
<section className="section bg-[#f7f3ea]"><div className="container"><SectionHeading eyebrow="What the journey can include" title="THE ESSENTIALS, THOUGHTFULLY ARRANGED.">Your confirmed itinerary will set out the exact hotels, transport and activities for your journey.</SectionHeading><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Premium hotels',Hotel],['Private transportation',Car],['Haramain Train',TrainFront],['Ziyarat & experiences',MapPinned]].map(([t,I])=><div className="card bg-white p-6" key={t as string}><I size={22} className="text-gold"/><h3 className="mt-4 font-semibold text-forest">{t as string}</h3><p className="mt-2 text-sm leading-6 text-forest/60">Planned according to your confirmed itinerary and package.</p></div>)}</div></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Plan with clarity" title="SEE YOUR ESTIMATED TOTAL.">Choose a package and guest count. The estimate updates instantly. Your request is not a booking confirmation.</SectionHeading><div className="mt-10"><PriceCalculator/></div></div></section>
<section className="section"><div className="container grid gap-10 md:grid-cols-3"><div className="md:col-span-2"><SectionHeading eyebrow="Jeddah — a little piece of home" title="CULTURE, SHOPPING AND CONNECTION.">Where included in the journey, experience Jeddah through selected cultural areas, shopping and an opportunity to visit the Somali Market.</SectionHeading><Link href="/jeddah" className="btn btn-primary mt-7">Explore Jeddah</Link></div><div className="card overflow-hidden"><img src={jeddah} alt="Jeddah architecture" className="h-full min-h-64 w-full object-cover"/></div></div></section>
<section className="section bg-[#eee9dc]"><div className="container text-center"><div className="eyebrow">Ready to begin?</div><h2 className="serif mx-auto mt-4 max-w-3xl text-5xl text-forest">LET’S PLAN YOUR JOURNEY.</h2><p className="mx-auto mt-5 max-w-2xl text-forest/60">You do not need a confirmed flight date. Share your expected travel date or period and our team will contact you personally to continue planning.</p><Link href="/request-journey" className="btn btn-primary mt-8">Request your journey</Link></div></section></main>}