import Link from 'next/link';
import {cookies} from 'next/headers';
import {defaultLocale,isLocale,messages} from '@/lib/i18n';
import {getSupabasePublicServer} from '@/lib/supabase/server';
import {ArrowRight,ShieldCheck,Users,HeartHandshake,Hotel,TrainFront,Car,MapPinned,Star} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
import {SectionHeading} from '@/components/ui/SectionHeading';
import {PriceCalculator} from '@/components/booking/PriceCalculator';

const hero='https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&w=2200&q=90';
const makkah='https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&w=1400&q=88';
const madinah='https://images.unsplash.com/photo-1635829581952-d507b68ef6b5?auto=format&fit=crop&w=1400&q=88';
const jeddah='https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1400&q=88';

const local={
 en:{premium:'Premium experience',higher:'Higher level',journeys:'OUR UMRAH JOURNEYS',choose:'CHOOSE THE JOURNEY THAT FITS YOUR PEOPLE.',packageIntro:'Two clear journeys. Transparent pricing. Thoughtful arrangements for small groups.',signature:'Comfortable & meaningful',elite:'A higher level of comfort',perGuest:'per guest',view:'View journey',real:'GUEST EXPERIENCES',realTitle:'Real experiences. Real people.',realIntro:'Verified guest reviews will appear here after journeys are completed and reviews are approved.',empty:'Your experience can be next.',emptyText:'We do not publish invented testimonials. Once our first guests share verified feedback, their words and city will appear here.',dest:'BEYOND UMRAH',destTitle:'Discover Makkah, Madinah & Jeddah',destText:'The sacred cities and the wider experience, thoughtfully arranged around your journey.',learn:'Explore',included:'THE DETAILS MATTER',includedText:'From accommodation and transport to ziyarat and personal support, the confirmed itinerary sets out exactly what is arranged.',request:'Request your journey',chat:'Chat on WhatsApp',process:'FROM INTEREST TO JOURNEY',steps:[['01','Choose','Select Signature or Elite.'],['02','Tell us your people','Choose 1–8 guests and your expected travel period.'],['03','Speak with us','We review the request and continue with you directly.'],['04','Confirm','Your final itinerary and payment instructions come before confirmation.']]},
 so:{premium:'Khibrad heer sare ah',higher:'Heer ka sarreeya',journeys:'SAFARRADEENNA CUMRADA',choose:'DOORO SAFARKA KU HABBOON DADKAAGA.',packageIntro:'Laba safar oo cad. Qiime cad. Qorshe taxaddar leh oo loogu talagalay kooxo yaryar.',signature:'Raaxo & macne',elite:'Heer raaxo oo sarreeya',perGuest:'qofkiiba',view:'Eeg safarka',real:'KHIBRADA MARTIDA',realTitle:'Khibrado dhab ah. Dad dhab ah.',realIntro:'Faallooyinka martida la xaqiijiyay waxay halkan kasoo muuqan doonaan marka safarradu dhamaadaan oo la ansixiyo.',empty:'Khibraddaadu waxay noqon kartaa tan xigta.',emptyText:'Ma daabacno markhaatiyo la sameeyay. Marka martideenna ugu horreysa ay bixiyaan faallo la xaqiijiyay, magacooda iyo magaaladooda ayaa halkan kasoo muuqan doona.',dest:'WAX KA BADAN CUMRO',destTitle:'Baro Makkah, Madiinah & Jeddah',destText:'Magaalooyinka barakeysan iyo khibradda ku xeeran, si taxaddar leh loogu habeeyay safarkaaga.',learn:'Sahami',included:'FAAHFAAHINTU WAA MUHIIM',includedText:'Laga bilaabo hoyga iyo gaadiidka ilaa ziyaraat iyo taageerada qofeed, jadwalka la xaqiijiyay wuxuu si cad u qeexayaa waxa la diyaariyay.',request:'Codso safarkaaga',chat:'Nala hadal WhatsApp',process:'LAGA BILAABO XIISAHA ILAA SAFARKA',steps:[['01','Dooro','Dooro Signature ama Elite.'],['02','Sheeg dadkaaga','Dooro 1–8 marti iyo muddada aad filayso.'],['03','Nala hadal','Waxaan dib u eegaynaa codsiga oo si toos ah ayaan kula sii wadaynaa.'],['04','Xaqiiji','Jadwalka ugu dambeeya iyo tilmaamaha lacag-bixinta ayaa yimaada ka hor xaqiijinta.']]},
 ar:{premium:'تجربة راقية',higher:'مستوى أعلى',journeys:'رحلات العمرة لدينا',choose:'اختر الرحلة التي تناسب مجموعتك.',packageIntro:'رحلتان واضحتان. أسعار شفافة. وترتيبات مدروسة للمجموعات الصغيرة.',signature:'راحة ومعنى',elite:'مستوى أعلى من الراحة',perGuest:'للضيف',view:'استكشف الرحلة',real:'تجارب الضيوف',realTitle:'تجارب حقيقية. أشخاص حقيقيون.',realIntro:'ستظهر تقييمات الضيوف الموثقة هنا بعد إتمام الرحلات ومراجعة التقييمات واعتمادها.',empty:'قد تكون تجربتك التالية.',emptyText:'لا ننشر شهادات مختلقة. عندما يشارك ضيوفنا الأوائل تجارب موثقة، سيظهر اسم الضيف ومدينته هنا.',dest:'أكثر من العمرة',destTitle:'اكتشف مكة والمدينة وجدة',destText:'المدن المقدسة وما حول الرحلة، بترتيب مدروس يتناسب مع تجربتك.',learn:'استكشف',included:'التفاصيل تصنع الفرق',includedText:'من الإقامة والتنقلات إلى الزيارات والدعم الشخصي، يوضح البرنامج المؤكد ما تم ترتيبه بالتحديد.',request:'اطلب رحلتك',chat:'تحدث معنا عبر واتساب',process:'من الاهتمام إلى الرحلة',steps:[['01','اختر','اختر SIGNATURE أو ELITE.'],['02','أخبرنا عن مجموعتك','حدد 1–8 ضيوف والفترة المتوقعة للسفر.'],['03','تحدث معنا','نراجع الطلب ونكمل معك مباشرة.'],['04','أكد','يصلك البرنامج النهائي وتعليمات الدفع قبل تأكيد الحجز.']]}
} as const;

export default async function Home(){
 const raw=(await cookies()).get('he_locale')?.value; const locale=isLocale(raw)?raw:defaultLocale; const t=messages[locale].home; const nav=messages[locale].nav; const c=local[locale];
 let reviews:any[]=[];
 try{const supabase=getSupabasePublicServer(); const r=await supabase.from('reviews').select('guest_name,country,rating,review_text,review_date').eq('status','PUBLISHED').eq('verified',true).order('review_date',{ascending:false}).limit(8); reviews=r.data||[]}catch{}
 const highlights:Array<[string,LucideIcon]>= [['Premium service',ShieldCheck],['Small groups',Users],['Personal support',HeartHandshake],['Thoughtful planning',MapPinned]];
 const essentials:Array<[string,LucideIcon]>= [['Premium hotels',Hotel],['Private transportation',Car],['Haramain Train',TrainFront],['Ziyarat & experiences',MapPinned]];
 const packages=[{name:'SIGNATURE',price:'$2,000',position:c.signature,image:makkah,href:'/packages/signature',tag:c.premium,desc:'Premium hotels, breakfast, private transportation, ziyarat, Jeddah experience, SIM and journey support.'},{name:'ELITE',price:'$2,500',position:c.elite,image:madinah,href:'/packages/elite',tag:c.higher,desc:'Luxury accommodation, breakfast, Haramain Train economy where applicable, private transportation, ziyarat, Jeddah experience, SIM and journey support.'}];
 return <main>
  <section className="relative min-h-[76vh] overflow-hidden bg-forest text-white"><img src={hero} alt="Kaaba at Masjid al-Haram in Makkah" className="absolute inset-0 h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-r from-forest/95 via-forest/70 to-forest/15"/><div className="absolute inset-0 bg-gradient-to-t from-forest/75 via-transparent to-transparent"/><div className="container relative flex min-h-[76vh] items-center py-24"><div className="max-w-3xl"><div className="eyebrow">{t.eyebrow}</div><h1 className="serif mt-5 text-6xl leading-[.95] md:text-8xl">{t.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/85">{t.intro}</p><p className="mt-4 max-w-2xl text-sm leading-7 text-white/65">{t.sub}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/packages" className="btn bg-gold text-forest">{t.explore} <ArrowRight size={16} className="ml-2"/></Link><Link href="/request-journey" className="btn border border-white/40 text-white">{nav.plan}</Link></div></div></div></section>

  <section className="border-b border-forest/10 bg-white py-5"><div className="container grid gap-4 sm:grid-cols-2 md:grid-cols-4">{highlights.map(([x,I])=><div className="flex items-center gap-3 text-sm text-forest/70" key={x}><I size={19} className="text-gold"/><span>{x}</span></div>)}</div></section>

  <section className="section"><div className="container"><SectionHeading eyebrow={c.journeys} title={c.choose}>{c.packageIntro}</SectionHeading><div className="mt-10 grid gap-7 lg:grid-cols-2">{packages.map((p,i)=><article key={p.name} className="overflow-hidden rounded-[28px] border border-forest/10 bg-white shadow-[0_25px_80px_rgba(6,63,53,.08)]"><div className="grid md:grid-cols-[.72fr_1.28fr]"><div className="relative min-h-64 overflow-hidden"><img src={p.image} alt={p.name==='ELITE'?'Madinah':'Makkah'} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-forest/70 to-transparent"/><span className="absolute left-5 top-5 rounded-full bg-white/90 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-forest">{p.tag}</span></div><div className="p-7 md:p-8"><div className="eyebrow">{p.name}</div><h3 className="serif mt-2 text-3xl text-forest">{p.position}</h3><div className="serif mt-3 text-5xl text-forest">{p.price}</div><div className="mt-1 text-sm text-forest/45">{c.perGuest} · 10 days / 9 nights</div><p className="mt-5 text-sm leading-6 text-forest/65">{p.desc}</p><Link href={p.href} className={`btn mt-7 ${i===1?'bg-gold text-forest':'btn-primary'} w-full`}>{c.view} <ArrowRight size={16} className="ml-2"/></Link></div></div></article>)}</div></div></section>

  <section className="section bg-[#f7f3ea]"><div className="container"><SectionHeading eyebrow={c.included} title={c.includedText}/><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{essentials.map(([title,I])=><div className="card bg-white p-6" key={title}><I size={23} className="text-gold"/><h3 className="mt-4 font-semibold text-forest">{title}</h3><p className="mt-2 text-sm leading-6 text-forest/55">{t.essentialsText}</p></div>)}</div></div></section>

  <section className="section"><div className="container"><SectionHeading eyebrow={c.real} title={c.realTitle}>{c.realIntro}</SectionHeading>{reviews.length>0?<div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{reviews.map((r)=><article key={r.guest_name+r.review_date} className="card p-6"><div className="flex gap-1">{Array.from({length:Math.min(5,Math.max(0,r.rating||0))}).map((_,i)=><Star key={i} size={15} fill="currentColor" className="text-gold"/></div><p className="mt-4 text-sm leading-6 text-forest/70">“{r.review_text}”</p><div className="mt-6 border-t border-forest/10 pt-4"><div className="font-semibold text-forest">{r.guest_name}</div><div className="text-xs text-forest/50">{r.country}</div></div></article>)}</div>:<div className="mt-9 grid gap-5 md:grid-cols-[1.1fr_1fr]"><div className="rounded-[28px] bg-forest p-8 text-white md:p-10"><div className="flex gap-1">{[1,2,3,4,5].map(i=><Star key={i} size={16} className="text-gold"/></div><h3 className="serif mt-5 text-3xl">{c.empty}</h3><p className="mt-4 max-w-xl leading-7 text-white/70">{c.emptyText}</p><Link href="/request-journey" className="btn mt-7 bg-gold text-forest">{c.request}</Link></div><div className="grid gap-4 sm:grid-cols-2">{[['01','Verified reviews','Published only after review and approval.'],['02','Guest name & city','Shown with the guest’s permission and approved review.'],['03','Real experiences','No stock testimonials or invented praise.'],['04','Built over time','Every completed journey can become a real story.']].map(([n,a,b])=><div className="card p-5" key={n}><div className="eyebrow">{n}</div><h4 className="mt-2 font-semibold text-forest">{a}</h4><p className="mt-2 text-sm leading-6 text-forest/55">{b}</p></div>)}</div></div>}</div></section>

  <section className="section bg-white"><div className="container"><SectionHeading eyebrow={c.dest} title={c.destTitle}>{c.destText}</SectionHeading><div className="mt-9 grid gap-5 md:grid-cols-3"><Link href="/makkah" className="group relative h-80 overflow-hidden rounded-[28px]"><img src={makkah} alt="Makkah" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute bottom-6 left-6 text-white"><div className="eyebrow text-gold">Makkah</div><div className="serif mt-1 text-3xl">The Sacred Mosque</div><span className="mt-3 inline-flex items-center text-sm">{c.learn} <ArrowRight size={15} className="ml-2"/></span></div></Link><Link href="/madinah" className="group relative h-80 overflow-hidden rounded-[28px]"><img src={madinah} alt="Madinah" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute bottom-6 left-6 text-white"><div className="eyebrow text-gold">Madinah</div><div className="serif mt-1 text-3xl">The Prophet’s Mosque</div><span className="mt-3 inline-flex items-center text-sm">{c.learn} <ArrowRight size={15} className="ml-2"/></span></div></Link><Link href="/jeddah" className="group relative h-80 overflow-hidden rounded-[28px]"><img src={jeddah} alt="Jeddah" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute bottom-6 left-6 text-white"><div className="eyebrow text-gold">Jeddah</div><div className="serif mt-1 text-3xl">Culture & the Red Sea</div><span className="mt-3 inline-flex items-center text-sm">{c.learn} <ArrowRight size={15} className="ml-2"/></span></div></Link></div></div></section>

  <section className="section bg-forest text-white"><div className="container"><div className="grid gap-8 md:grid-cols-[1.2fr_.8fr] md:items-center"><div><div className="eyebrow">{c.process}</div><h2 className="serif mt-4 text-5xl">{t.finalTitle}</h2><p className="mt-4 max-w-2xl leading-8 text-white/70">{t.finalText}</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/request-journey" className="btn bg-gold text-forest">{c.request}</Link><a href="https://wa.me/966579120989" className="btn border border-white/30 text-white">{c.chat}</a></div></div><div className="grid gap-3 sm:grid-cols-2">{c.steps.map(([n,a,b])=><div className="rounded-2xl border border-white/10 bg-white/5 p-5" key={n}><div className="eyebrow">{n}</div><h3 className="serif mt-2 text-2xl">{a}</h3><p className="mt-2 text-sm leading-6 text-white/60">{b}</p></div>)}</div></div></div></section>
 </main>;
}