import Link from 'next/link';
import { cookies } from 'next/headers';
import { defaultLocale, isLocale, messages } from '@/lib/i18n';
import { ArrowRight, ShieldCheck, Users, HeartHandshake, Hotel, TrainFront, Car, MapPinned } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { SectionHeading } from '@/components/ui/SectionHeading';
import { PriceCalculator } from '@/components/booking/PriceCalculator';

const hero='https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&w=2200&q=90';
const jeddah='https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1200&q=85';

export default async function Home(){
  const raw=(await cookies()).get('he_locale')?.value;
  const locale=isLocale(raw)?raw:defaultLocale;
  const t=messages[locale].home;
  const nav=messages[locale].nav;
  const cards: Array<[string, string, string]> = [[ '01',t.cards.comfort,t.cards.comfortText ],[ '02',t.cards.support,t.cards.supportText ],[ '03',t.cards.groups,t.cards.groupsText ],[ '04',t.cards.connection,t.cards.connectionText ]];
  const highlights: Array<[string, LucideIcon]> = [['Premium service',ShieldCheck],['Small groups',Users],['Personal support',HeartHandshake],['Thoughtful planning',MapPinned]];
  const essentials: Array<[string, LucideIcon]> = [['Premium hotels',Hotel],['Private transportation',Car],['Haramain Train',TrainFront],['Ziyarat & experiences',MapPinned]];
  return <main>
    <section className="relative min-h-[78vh] overflow-hidden bg-forest text-white"><img src={hero} alt="Makkah and the Kaaba" className="absolute inset-0 h-full w-full object-cover opacity-55 scale-[1.03]"/><div className="absolute inset-0 bg-gradient-to-r from-forest/95 via-forest/65 to-forest/10"/><div className="absolute inset-0 bg-gradient-to-t from-forest/70 via-transparent to-transparent"/><div className="container relative flex min-h-[78vh] items-center py-24"><div className="max-w-3xl"><div className="eyebrow">{t.eyebrow}</div><h1 className="serif mt-5 text-6xl leading-[.95] md:text-8xl">{t.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/80">{t.intro}</p><p className="mt-4 max-w-2xl text-sm leading-7 text-white/60">{t.sub}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/request-journey" className="btn bg-gold text-forest">{nav.plan}</Link><Link href="/packages" className="btn border border-white/40 text-white">{t.explore}</Link></div></div></div></section>
    <section className="border-b border-forest/10 bg-white py-6"><div className="container grid gap-5 text-sm text-forest/70 md:grid-cols-4">{highlights.map(([x,I])=><div className="flex items-center gap-3" key={x as string}><I size={18} className="text-gold"/>{x as string}</div>)}</div></section>
    <section className="section"><div className="container grid gap-12 md:grid-cols-2 md:items-center"><SectionHeading eyebrow={t.moreEyebrow} title={t.moreTitle}>{t.moreText}</SectionHeading><div className="grid grid-cols-2 gap-4">{cards.map(([n,title,text])=><div className="card p-6" key={n}><div className="eyebrow">{n}</div><h3 className="serif mt-3 text-2xl text-forest">{title}</h3><p className="mt-3 text-sm leading-6 text-forest/60">{text}</p></div>)}</div></div></section>
    <section className="section bg-forest text-white"><div className="container"><SectionHeading eyebrow={t.madeEyebrow} title={t.madeTitle} inverse><span className="text-white/70">{t.madeText}</span></SectionHeading></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow={t.packagesEyebrow} title={t.packagesTitle}>{t.packagesText}</SectionHeading><div className="mt-10 grid gap-6 md:grid-cols-2">{[['SIGNATURE','$2,000','Premium hotels, breakfast, private transportation, ziyarat, Jeddah experience, SIM and journey support.','/packages/signature'],['ELITE','$2,500','Luxury accommodation, breakfast, Haramain Train economy class, private transportation, ziyarat, Jeddah experience, SIM and journey support.','/packages/elite']].map(([n,p,d,h],i)=><article className={`card p-8 ${i===1?'border-gold':''}`} key={n}><div className="eyebrow">{n}</div><div className="serif mt-4 text-5xl text-forest">{p}</div><p className="mt-2 text-sm text-forest/50">per guest · 10 days / 9 nights</p><p className="mt-7 leading-7 text-forest/70">{d}</p><Link href={h} className="btn btn-outline mt-8">{nav.packages} <ArrowRight size={16} className="ml-2"/></Link></article>)}</div></div></section>
    <section className="section bg-[#f7f3ea]"><div className="container"><SectionHeading eyebrow={t.essentialsEyebrow} title={t.essentialsTitle}>{t.essentialsText}</SectionHeading><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{essentials.map(([title,I])=><div className="card bg-white p-6" key={title as string}><I size={22} className="text-gold"/><h3 className="mt-4 font-semibold text-forest">{title as string}</h3><p className="mt-2 text-sm leading-6 text-forest/60">{t.essentialsText}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow={t.clarityEyebrow} title={t.clarityTitle}>{t.clarityText}</SectionHeading><div className="mt-10"><PriceCalculator/></div></div></section>
    <section className="section"><div className="container grid gap-10 md:grid-cols-3"><div className="md:col-span-2"><SectionHeading eyebrow={t.jeddahEyebrow} title={t.jeddahTitle}>{t.jeddahText}</SectionHeading><Link href="/jeddah" className="btn btn-primary mt-7">{t.jeddahCta}</Link></div><div className="card overflow-hidden"><img src={jeddah} alt="Jeddah architecture" className="h-full min-h-64 w-full object-cover"/></div></div></section>
    <section className="section bg-[#eee9dc]"><div className="container text-center"><div className="eyebrow">{t.finalEyebrow}</div><h2 className="serif mx-auto mt-4 max-w-3xl text-5xl text-forest">{t.finalTitle}</h2><p className="mx-auto mt-5 max-w-2xl text-forest/60">{t.finalText}</p><Link href="/request-journey" className="btn btn-primary mt-8">{t.finalCta}</Link></div></section>
  </main>;
}