export const adminText={
  en:{
    workspace:'Workspace',dashboard:'Dashboard',requests:'Journey Requests',customers:'Customers',journeys:'Journeys',bookings:'Bookings',operations:'Operations & Tasks',groups:'Groups',resources:'Resources',payments:'Payments',expenses:'Expenses',reports:'Reports',audit:'Audit Logs',communications:'Communications',reviews:'Reviews',team:'Team & Permissions',settings:'Settings',
    signIn:'Admin sign in.',privateAccess:'Private access',email:'Email',password:'Password',signingIn:'Signing in…',login:'Sign in',signOut:'Sign out',signingOut:'Signing out…',
    executive:'Executive workspace',sales:'Sales workspace',ops:'Operations workspace',execIntro:'See what needs attention across sales, payments and upcoming journeys.',salesIntro:'Work the customer journey from first request to confirmed handover.',opsIntro:'Prepare every confirmed journey and keep the next operational action visible.',
    openJourneys:'Open journeys',newRequests:'New requests',activeJourneys:'Active journeys',paymentActions:'Payment actions',operationalIssues:'Operational issues',recentJourneys:'Recent journeys',viewAll:'View all →',needsAttention:'Needs attention',businessSnapshot:'Business snapshot',paymentsReceived:'Payments received',completedJourneys:'Completed journeys',nothingUrgent:'Nothing urgent right now.',operatingModel:'Your operating model',inbox:'INBOX',followup:'Requests & follow-up',journeyFile:'JOURNEYS',customerBooking:'Customer + booking file',operationsLabel:'OPERATIONS',readiness:'Readiness & resources',management:'MANAGEMENT',financeTeam:'Finance, reports & team',
    journeyWorkspace:'Journey workspace',journeyWorkspaceDesc:'One place for the customer, package, payment and operational readiness of every journey.',activeCount:'active journeys',noJourneys:'No journeys yet.',journey:'Journey',value:'Value',stage:'Journey stage',open:'Open →',customer:'Customer',package:'Package',guests:'guests',country:'Country',notSet:'Not set',until:'Until',unnamed:'Unnamed customer',financial:'Financial',journeyValue:'Journey value',payment:'Payment',communication:'Communication',openPayments:'Open payments',operationsReadiness:'Operations readiness',hotels:'Hotels',transportation:'Transportation',train:'Train',ziyaraHost:'Ziyarat / Host',openOperations:'Open Operations Control Center',noNotes:'No notes yet.',
    managementTitle:'Team & Permissions',managementDesc:'Create employee accounts, assign the right role and control access without sharing passwords.',createStaff:'Create staff account',invite:'Invite a team member',inviteDesc:'The employee receives an invitation by email, then creates their own password. You never need to share a password.',fullName:'Full name',workEmail:'Work email',phone:'WhatsApp / phone',sendInvitation:'Send invitation',working:'Working…',permissionModel:'Permission model',roleAccess:'Role-based access',teamAccounts:'Staff accounts',employee:'Employee',role:'Role',account:'Account',joined:'Joined',access:'Access',activeEmail:'Active email',invitationPending:'Invitation pending',deactivate:'Deactivate account',reactivate:'Reactivate account',invitationSent:'Invitation sent. The employee will set their password from the email link.',accessUpdated:'Access updated.',
  },
  ar:{
    workspace:'مساحة العمل',dashboard:'لوحة التحكم',requests:'طلبات الرحلات',customers:'العملاء',journeys:'الرحلات',bookings:'الحجوزات',operations:'العمليات والمهام',groups:'المجموعات',resources:'الموارد',payments:'المدفوعات',expenses:'المصروفات',reports:'التقارير',audit:'سجل النشاط',communications:'التواصل',reviews:'التقييمات',team:'الفريق والصلاحيات',settings:'الإعدادات',
    signIn:'تسجيل دخول الإدارة',privateAccess:'دخول خاص',email:'البريد الإلكتروني',password:'كلمة المرور',signingIn:'جارٍ تسجيل الدخول…',login:'دخول',signOut:'تسجيل الخروج',signingOut:'جارٍ تسجيل الخروج…',
    executive:'مساحة الإدارة',sales:'مساحة المبيعات',ops:'مساحة العمليات',execIntro:'تابع ما يحتاج إلى اهتمام في المبيعات والمدفوعات والرحلات القادمة.',salesIntro:'أدر رحلة العميل من أول طلب حتى تسليمه إلى العمليات بعد التأكيد.',opsIntro:'جهّز كل رحلة مؤكدة وتابع الإجراء التشغيلي التالي بوضوح.',
    openJourneys:'فتح الرحلات',newRequests:'الطلبات الجديدة',activeJourneys:'الرحلات النشطة',paymentActions:'إجراءات الدفع',operationalIssues:'المشكلات التشغيلية',recentJourneys:'أحدث الرحلات',viewAll:'عرض الكل ←',needsAttention:'يحتاج إلى اهتمام',businessSnapshot:'ملخص الأعمال',paymentsReceived:'المدفوعات المستلمة',completedJourneys:'الرحلات المكتملة',nothingUrgent:'لا توجد أمور عاجلة حاليًا.',operatingModel:'نموذج العمل',inbox:'الوارد',followup:'الطلبات والمتابعة',journeyFile:'الرحلات',customerBooking:'ملف العميل والحجز',operationsLabel:'العمليات',readiness:'الجاهزية والموارد',management:'الإدارة',financeTeam:'المالية والتقارير والفريق',
    journeyWorkspace:'مساحة الرحلات',journeyWorkspaceDesc:'مكان واحد يجمع العميل والباقة والدفع والجاهزية التشغيلية لكل رحلة.',activeCount:'رحلة نشطة',noJourneys:'لا توجد رحلات حتى الآن.',journey:'الرحلة',value:'القيمة',stage:'مرحلة الرحلة',open:'فتح ←',customer:'العميل',package:'الباقة',guests:'ضيوف',country:'الدولة',notSet:'غير محدد',until:'حتى',unnamed:'عميل بدون اسم',financial:'المالية',journeyValue:'قيمة الرحلة',payment:'الدفع',communication:'التواصل',openPayments:'فتح المدفوعات',operationsReadiness:'الجاهزية التشغيلية',hotels:'الفنادق',transportation:'النقل',train:'القطار',ziyaraHost:'الزيارات / المضيف',openOperations:'فتح مركز العمليات',noNotes:'لا توجد ملاحظات.',
    managementTitle:'الفريق والصلاحيات',managementDesc:'أنشئ حسابات الموظفين، وحدد أدوارهم، وتحكم في الوصول دون مشاركة كلمات المرور.',createStaff:'إنشاء حساب موظف',invite:'دعوة عضو للفريق',inviteDesc:'سيتلقى الموظف دعوة عبر البريد ثم ينشئ كلمة المرور بنفسه. لا حاجة لمشاركة أي كلمة مرور.',fullName:'الاسم الكامل',workEmail:'بريد العمل',phone:'واتساب / الهاتف',sendInvitation:'إرسال الدعوة',working:'جارٍ التنفيذ…',permissionModel:'نموذج الصلاحيات',roleAccess:'الوصول حسب الدور',teamAccounts:'حسابات الموظفين',employee:'الموظف',role:'الدور',account:'الحساب',joined:'تاريخ الانضمام',access:'الوصول',activeEmail:'البريد مفعّل',invitationPending:'الدعوة بانتظار التفعيل',deactivate:'تعطيل الحساب',reactivate:'إعادة تفعيل الحساب',invitationSent:'تم إرسال الدعوة. سيقوم الموظف بإنشاء كلمة المرور من الرابط المرسل.',accessUpdated:'تم تحديث الصلاحية.'
  }
} as const;
