export const adminText={
  en:{
    workspace:'Workspace',dashboard:'Dashboard',requests:'Journey Requests',customers:'Customers',journeys:'Journeys',bookings:'Bookings',operations:'Operations & Tasks',groups:'Groups',resources:'Resources',payments:'Payments',expenses:'Expenses',reports:'Reports',audit:'Audit Logs',communications:'Communications',reviews:'Reviews',team:'Team & Permissions',settings:'Settings',
    signIn:'Admin sign in.',privateAccess:'Private access',email:'Email',password:'Password',signingIn:'Signing in…',login:'Sign in',signOut:'Sign out',signingOut:'Signing out…',
    executive:'Executive workspace',sales:'Sales workspace',ops:'Operations workspace',execIntro:'See what needs attention across sales, payments and upcoming journeys.',salesIntro:'Work the customer journey from first request to confirmed handover.',opsIntro:'Prepare every confirmed journey and keep the next operational action visible.',
    openJourneys:'Open journeys',newRequests:'New requests',activeJourneys:'Active journeys',paymentActions:'Payment actions',operationalIssues:'Operational issues',recentJourneys:'Recent journeys',viewAll:'View all →',needsAttention:'Needs attention',businessSnapshot:'Business snapshot',paymentsReceived:'Payments received',completedJourneys:'Completed journeys',nothingUrgent:'Nothing urgent right now.',operatingModel:'Your operating model',inbox:'INBOX',followup:'Requests & follow-up',journeyFile:'JOURNEYS',customerBooking:'Customer + booking file',operationsLabel:'OPERATIONS',readiness:'Readiness & resources',management:'MANAGEMENT',financeTeam:'Finance, reports & team',
    page:{requests:'Journey Requests',bookings:'Bookings',operations:'Operations',guests:'Guests',hosts:'Hosts',hotels:'Hotels',groups:'Groups',payments:'Payments',expenses:'Expenses',reports:'Reports',reviews:'Reviews',settings:'Settings',train:'Train bookings',communications:'Communication templates',audit:'Audit logs',influencers:'Influencer Partners'},common:{workspace:'Workspace',salesWorkspace:'Sales workspace',salesFinance:'Sales & finance',opsManager:'Operations manager',operationsManager:'Operations manager',finance:'Finance',database:'Database',noRequests:'No journey requests yet.',noBookings:'No bookings yet.',noTasks:'No operational tasks yet.',noGuests:'No guest records yet.',noHosts:'No hosts registered yet.',noHotels:'No hotel records yet.',noGroups:'No groups created yet.',noPayments:'No payment records yet.',noExpenses:'No expense records yet.',noReviews:'No review records yet.',noTemplates:'No communication templates yet.',noAudit:'No audit entries yet.',reviewIncoming:'Review incoming journey requests before confirming any booking.',trackBookings:'Track booking lifecycle and payment status. A journey request is not a confirmed booking.',operationsDesc:'Day-to-day tasks, assignments and journey readiness.',guestsDesc:'Guest records linked to journey bookings.',hostsDesc:'Operational host resources. Hosts do not receive Admin accounts.',hotelsDesc:'Live hotel records and availability status.',paymentsDesc:'Manual bank-transfer tracking. Finance verification controls booking payment state.',expensesDesc:'Journey and operational costs.',trainDesc:'Haramain Train records linked to groups.',communicationsDesc:'Prepared messages for manual WhatsApp follow-up.',auditDesc:'Immutable operational history for sensitive admin actions.',reviewsDesc:'Only verified guest experiences should be published.',settingsDesc:'Operational configuration.'},
    journeyWorkspace:'Journey workspace',journeyWorkspaceDesc:'One place for the customer, package, payment and operational readiness of every journey.',activeCount:'active journeys',noJourneys:'No journeys yet.',journey:'Journey',value:'Value',stage:'Journey stage',open:'Open →',customer:'Customer',package:'Package',guests:'guests',country:'Country',notSet:'Not set',until:'Until',unnamed:'Unnamed customer',financial:'Financial',journeyValue:'Journey value',payment:'Payment',communication:'Communication',openPayments:'Open payments',operationsReadiness:'Operations readiness',hotels:'Hotels',transportation:'Transportation',train:'Train',ziyaraHost:'Ziyarat / Host',openOperations:'Open Operations Control Center',noNotes:'No notes yet.',
    managementTitle:'Team & Permissions',managementDesc:'Create employee accounts, assign the right role and control access without sharing passwords.',createStaff:'Create staff account',invite:'Invite a team member',inviteDesc:'The employee receives an invitation by email, then creates their own password. You never need to share a password.',fullName:'Full name',workEmail:'Work email',phone:'WhatsApp / phone',sendInvitation:'Send invitation',working:'Working…',permissionModel:'Permission model',roleAccess:'Role-based access',teamAccounts:'Staff accounts',employee:'Employee',role:'Role',account:'Account',joined:'Joined',access:'Access',activeEmail:'Active email',invitationPending:'Invitation pending',deactivate:'Deactivate account',reactivate:'Reactivate account',invitationSent:'Invitation sent. The employee will set their password from the email link.',accessUpdated:'Access updated.',
  },
  ar:{
    page:{requests:'طلبات الرحلات',bookings:'الحجوزات',operations:'العمليات',guests:'الضيوف',hosts:'المضيفون',hotels:'الفنادق',groups:'المجموعات',payments:'المدفوعات',expenses:'المصروفات',reports:'التقارير',reviews:'التقييمات',settings:'الإعدادات',train:'حجوزات قطار الحرمين',communications:'قوالب التواصل',audit:'سجل النشاط',influencers:'شركاء المؤثرين'},common:{workspace:'مساحة العمل',salesWorkspace:'مساحة المبيعات',salesFinance:'المبيعات والمالية',opsManager:'مدير العمليات',operationsManager:'مدير العمليات',finance:'المالية',database:'قاعدة البيانات',noRequests:'لا توجد طلبات رحلات حتى الآن.',noBookings:'لا توجد حجوزات حتى الآن.',noTasks:'لا توجد مهام تشغيلية حتى الآن.',noGuests:'لا توجد سجلات ضيوف حتى الآن.',noHosts:'لا يوجد مضيفون مسجلون حتى الآن.',noHotels:'لا توجد سجلات فنادق حتى الآن.',noGroups:'لا توجد مجموعات منشأة حتى الآن.',noPayments:'لا توجد سجلات مدفوعات حتى الآن.',noExpenses:'لا توجد سجلات مصروفات حتى الآن.',noReviews:'لا توجد تقييمات حتى الآن.',noTemplates:'لا توجد قوالب تواصل حتى الآن.',noAudit:'لا توجد سجلات نشاط حتى الآن.',reviewIncoming:'راجع طلبات الرحلات الواردة قبل تأكيد أي حجز.',trackBookings:'تابع دورة الحجز وحالة الدفع. طلب الرحلة لا يعني أن الحجز مؤكد.',operationsDesc:'المهام اليومية والتعيينات وجاهزية الرحلات.',guestsDesc:'سجلات الضيوف المرتبطة بحجوزات الرحلات.',hostsDesc:'موارد المضيفين التشغيلية. المضيفون لا يملكون حسابات إدارية.',hotelsDesc:'سجلات الفنادق وحالة التوفر الحالية.',paymentsDesc:'متابعة التحويلات البنكية اليدوية. المالية تتحكم في حالة التحقق من الدفع.',expensesDesc:'تكاليف الرحلات والعمليات.',trainDesc:'سجلات قطار الحرمين المرتبطة بالمجموعات.',communicationsDesc:'رسائل جاهزة للمتابعة اليدوية عبر واتساب.',auditDesc:'سجل تشغيلي غير قابل للتغيير للإجراءات الإدارية الحساسة.',reviewsDesc:'يجب نشر تجارب الضيوف التي تم التحقق منها فقط.',settingsDesc:'الإعدادات التشغيلية.'},
    workspace:'مساحة العمل',dashboard:'لوحة التحكم',requests:'طلبات الرحلات',customers:'العملاء',journeys:'الرحلات',bookings:'الحجوزات',operations:'العمليات والمهام',groups:'المجموعات',resources:'الموارد',payments:'المدفوعات',expenses:'المصروفات',reports:'التقارير',audit:'سجل النشاط',communications:'التواصل',reviews:'التقييمات',team:'الفريق والصلاحيات',settings:'الإعدادات',
    signIn:'تسجيل دخول الإدارة',privateAccess:'دخول خاص',email:'البريد الإلكتروني',password:'كلمة المرور',signingIn:'جارٍ تسجيل الدخول…',login:'دخول',signOut:'تسجيل الخروج',signingOut:'جارٍ تسجيل الخروج…',
    executive:'مساحة الإدارة',sales:'مساحة المبيعات',ops:'مساحة العمليات',execIntro:'تابع ما يحتاج إلى اهتمام في المبيعات والمدفوعات والرحلات القادمة.',salesIntro:'أدر رحلة العميل من أول طلب حتى تسليمه إلى العمليات بعد التأكيد.',opsIntro:'جهّز كل رحلة مؤكدة وتابع الإجراء التشغيلي التالي بوضوح.',
    openJourneys:'فتح الرحلات',newRequests:'الطلبات الجديدة',activeJourneys:'الرحلات النشطة',paymentActions:'إجراءات الدفع',operationalIssues:'المشكلات التشغيلية',recentJourneys:'أحدث الرحلات',viewAll:'عرض الكل ←',needsAttention:'يحتاج إلى اهتمام',businessSnapshot:'ملخص الأعمال',paymentsReceived:'المدفوعات المستلمة',completedJourneys:'الرحلات المكتملة',nothingUrgent:'لا توجد أمور عاجلة حاليًا.',operatingModel:'نموذج العمل',inbox:'الوارد',followup:'الطلبات والمتابعة',journeyFile:'الرحلات',customerBooking:'ملف العميل والحجز',operationsLabel:'العمليات',readiness:'الجاهزية والموارد',management:'الإدارة',financeTeam:'المالية والتقارير والفريق',
    journeyWorkspace:'مساحة الرحلات',journeyWorkspaceDesc:'مكان واحد يجمع العميل والباقة والدفع والجاهزية التشغيلية لكل رحلة.',activeCount:'رحلة نشطة',noJourneys:'لا توجد رحلات حتى الآن.',journey:'الرحلة',value:'القيمة',stage:'مرحلة الرحلة',open:'فتح ←',customer:'العميل',package:'الباقة',guests:'ضيوف',country:'الدولة',notSet:'غير محدد',until:'حتى',unnamed:'عميل بدون اسم',financial:'المالية',journeyValue:'قيمة الرحلة',payment:'الدفع',communication:'التواصل',openPayments:'فتح المدفوعات',operationsReadiness:'الجاهزية التشغيلية',hotels:'الفنادق',transportation:'النقل',train:'القطار',ziyaraHost:'الزيارات / المضيف',openOperations:'فتح مركز العمليات',noNotes:'لا توجد ملاحظات.',
    managementTitle:'الفريق والصلاحيات',managementDesc:'أنشئ حسابات الموظفين، وحدد أدوارهم، وتحكم في الوصول دون مشاركة كلمات المرور.',createStaff:'إنشاء حساب موظف',invite:'دعوة عضو للفريق',inviteDesc:'سيتلقى الموظف دعوة عبر البريد ثم ينشئ كلمة المرور بنفسه. لا حاجة لمشاركة أي كلمة مرور.',fullName:'الاسم الكامل',workEmail:'بريد العمل',phone:'واتساب / الهاتف',sendInvitation:'إرسال الدعوة',working:'جارٍ التنفيذ…',permissionModel:'نموذج الصلاحيات',roleAccess:'الوصول حسب الدور',teamAccounts:'حسابات الموظفين',employee:'الموظف',role:'الدور',account:'الحساب',joined:'تاريخ الانضمام',access:'الوصول',activeEmail:'البريد مفعّل',invitationPending:'الدعوة بانتظار التفعيل',deactivate:'تعطيل الحساب',reactivate:'إعادة تفعيل الحساب',invitationSent:'تم إرسال الدعوة. سيقوم الموظف بإنشاء كلمة المرور من الرابط المرسل.',accessUpdated:'تم تحديث الصلاحية.'
  }
} as const;

// Admin translations are shared by server and client-safe admin UI.

// Deployment checkpoint: admin client/server translation split is complete.
