export type CitySeo = {
  slug:string; city:string; country:string; countryCode:string; airport:string;
  title:string; description:string; areas:string[]; localNote:string; travelNote:string;
};

export const CITY_SEO: CitySeo[] = [
  {slug:'london',city:'London',country:'United Kingdom',countryCode:'UK',airport:'LHR / LGW',title:'Umrah from London for Somali Muslims',description:'Plan a premium small-group Umrah journey from London for Somali Muslims with clear pricing, 5–8 guest groups and personal support.',areas:['Brent','Newham','Tower Hamlets','East London'],localNote:'A London-focused planning page for Somali families and friends arranging an Umrah journey together from the UK.',travelNote:'Choose an expected travel period first; the final flight and itinerary details are confirmed with the journey team.'},
  {slug:'birmingham',city:'Birmingham',country:'United Kingdom',countryCode:'UK',airport:'BHX',title:'Umrah from Birmingham for Somali Muslims',description:'Plan a premium small-group Umrah journey from Birmingham for Somali Muslims with transparent packages and personal support.',areas:['Birmingham','West Midlands','Small Heath','Sparkbrook'],localNote:'Built for Somali travelers in Birmingham and the wider West Midlands who want a clear group Umrah planning process.',travelNote:'Start with your expected period and guest count. You do not need a confirmed flight date to send a journey request.'},
  {slug:'manchester',city:'Manchester',country:'United Kingdom',countryCode:'UK',airport:'MAN',title:'Umrah from Manchester for Somali Muslims',description:'Plan a premium small-group Umrah journey from Manchester for Somali Muslims with transparent packages and personal support.',areas:['Manchester','Greater Manchester','Longsight','Hulme'],localNote:'A Manchester-focused Umrah planning page for Somali Muslims arranging a shared journey with family or friends.',travelNote:'Your expected travel period is enough to begin planning; final travel details are confirmed later.'},
  {slug:'leicester',city:'Leicester',country:'United Kingdom',countryCode:'UK',airport:'EMA / BHX',title:'Umrah from Leicester for Somali Muslims',description:'Plan a premium small-group Umrah journey from Leicester for Somali Muslims with transparent packages and personal support.',areas:['Leicester','Leicestershire','East Leicester'],localNote:'A local starting point for Somali Muslims in Leicester who want a small-group Umrah journey with transparent pricing.',travelNote:'Send your preferred period and group size first, then the team can continue the itinerary conversation with you.'},
  {slug:'bristol',city:'Bristol',country:'United Kingdom',countryCode:'UK',airport:'BRS',title:'Umrah from Bristol for Somali Muslims',description:'Plan a premium small-group Umrah journey from Bristol for Somali Muslims with transparent packages and personal support.',areas:['Bristol','South West England','Bristol area'],localNote:'A city-specific planning page for Somali travelers in Bristol and the surrounding South West area.',travelNote:'Use an expected travel period rather than waiting for confirmed flights before contacting the team.'},
  {slug:'sheffield',city:'Sheffield',country:'United Kingdom',countryCode:'UK',airport:'MAN / LBA',title:'Umrah from Sheffield for Somali Muslims',description:'Plan a premium small-group Umrah journey from Sheffield for Somali Muslims with transparent packages and personal support.',areas:['Sheffield','South Yorkshire','Yorkshire'],localNote:'For Somali families and friends in Sheffield and South Yorkshire looking for a straightforward Umrah planning route.',travelNote:'Group planning starts with 5–8 guests and an expected travel date or period.'},
  {slug:'cardiff',city:'Cardiff',country:'United Kingdom',countryCode:'UK',airport:'CWL / BRS',title:'Umrah from Cardiff for Somali Muslims',description:'Plan a premium small-group Umrah journey from Cardiff for Somali Muslims with transparent packages and personal support.',areas:['Cardiff','South Wales','Newport area'],localNote:'A dedicated Cardiff starting point for Somali Muslims in South Wales planning Umrah together.',travelNote:'The initial request can use an expected travel period; confirmed flights are handled separately.'},

  {slug:'minneapolis',city:'Minneapolis',country:'United States',countryCode:'USA',airport:'MSP',title:'Umrah from Minneapolis for Somali Muslims',description:'Plan a premium small-group Umrah journey from Minneapolis for Somali Muslims with clear pricing, 5–8 guest groups and personal support.',areas:['Minneapolis','Twin Cities','Cedar-Riverside','South Minneapolis'],localNote:'A Minneapolis-focused Umrah planning page for Somali Muslims in the Twin Cities arranging family and community journeys.',travelNote:'Begin with your group size and expected period. The journey team can work through final flight and itinerary details afterward.'},
  {slug:'saint-paul',city:'Saint Paul',country:'United States',countryCode:'USA',airport:'MSP',title:'Umrah from Saint Paul for Somali Muslims',description:'Plan a premium small-group Umrah journey from Saint Paul for Somali Muslims with transparent packages and personal support.',areas:['Saint Paul','Twin Cities','Minnesota'],localNote:'Designed for Somali travelers in Saint Paul and the wider Twin Cities who want a clear small-group Umrah request process.',travelNote:'You can request a journey before your flights are confirmed.'},
  {slug:'columbus',city:'Columbus',country:'United States',countryCode:'USA',airport:'CMH',title:'Umrah from Columbus for Somali Muslims',description:'Plan a premium small-group Umrah journey from Columbus for Somali Muslims with transparent packages and personal support.',areas:['Columbus','Central Ohio','Franklin County'],localNote:'A Columbus-specific page for Somali Muslims in Central Ohio planning a premium small-group Umrah journey.',travelNote:'Share your expected travel period and group size to begin; confirmed flight information comes later.'},
  {slug:'seattle',city:'Seattle',country:'United States',countryCode:'USA',airport:'SEA',title:'Umrah from Seattle for Somali Muslims',description:'Plan a premium small-group Umrah journey from Seattle for Somali Muslims with transparent packages and personal support.',areas:['Seattle','Puget Sound','King County'],localNote:'A Seattle starting point for Somali Muslims across the Puget Sound area who are organizing Umrah together.',travelNote:'Use an expected travel period when submitting your request rather than waiting for a confirmed flight.'},
  {slug:'washington-dc',city:'Washington, DC',country:'United States',countryCode:'USA',airport:'DCA / IAD',title:'Umrah from Washington, DC for Somali Muslims',description:'Plan a premium small-group Umrah journey from Washington, DC for Somali Muslims with transparent packages and personal support.',areas:['Washington, DC','Northern Virginia','Maryland','DMV'],localNote:'A DMV-focused page for Somali Muslims in Washington, DC, Northern Virginia and Maryland planning Umrah in small groups.',travelNote:'Start with the expected period and number of guests; the final itinerary and flights are confirmed separately.'},
  {slug:'san-diego',city:'San Diego',country:'United States',countryCode:'USA',airport:'SAN',title:'Umrah from San Diego for Somali Muslims',description:'Plan a premium small-group Umrah journey from San Diego for Somali Muslims with transparent packages and personal support.',areas:['San Diego','San Diego County','Southern California'],localNote:'A dedicated San Diego planning page for Somali Muslims arranging Umrah with family or friends in Southern California.',travelNote:'An expected travel period is enough to start a request.'},
  {slug:'atlanta',city:'Atlanta',country:'United States',countryCode:'USA',airport:'ATL',title:'Umrah from Atlanta for Somali Muslims',description:'Plan a premium small-group Umrah journey from Atlanta for Somali Muslims with transparent packages and personal support.',areas:['Atlanta','Metro Atlanta','Georgia'],localNote:'A Metro Atlanta planning page for Somali Muslims looking for a transparent, small-group Umrah process.',travelNote:'Choose your expected period and group size before final flight details are confirmed.'},

  {slug:'toronto',city:'Toronto',country:'Canada',countryCode:'Canada',airport:'YYZ',title:'Umrah from Toronto for Somali Muslims',description:'Plan a premium small-group Umrah journey from Toronto for Somali Muslims with clear pricing, 5–8 guest groups and personal support.',areas:['Toronto','Greater Toronto Area','Rexdale','North York'],localNote:'A Toronto-focused page for Somali Muslims across the GTA planning Umrah with family and friends.',travelNote:'Begin with your expected period and guest count; the final flight and itinerary are confirmed separately.'},
  {slug:'ottawa',city:'Ottawa',country:'Canada',countryCode:'Canada',airport:'YOW',title:'Umrah from Ottawa for Somali Muslims',description:'Plan a premium small-group Umrah journey from Ottawa for Somali Muslims with transparent packages and personal support.',areas:['Ottawa','National Capital Region','Ontario'],localNote:'A local planning page for Somali Muslims in Ottawa arranging a small-group Umrah journey.',travelNote:'You can begin without a confirmed flight date.'},
  {slug:'edmonton',city:'Edmonton',country:'Canada',countryCode:'Canada',airport:'YEG',title:'Umrah from Edmonton for Somali Muslims',description:'Plan a premium small-group Umrah journey from Edmonton for Somali Muslims with transparent packages and personal support.',areas:['Edmonton','Edmonton area','Alberta'],localNote:'A dedicated Edmonton page for Somali Muslims in Alberta planning a transparent Umrah journey.',travelNote:'Share an expected travel period and 5–8 guest group size to begin.'},
  {slug:'calgary',city:'Calgary',country:'Canada',countryCode:'Canada',airport:'YYC',title:'Umrah from Calgary for Somali Muslims',description:'Plan a premium small-group Umrah journey from Calgary for Somali Muslims with transparent packages and personal support.',areas:['Calgary','Calgary area','Alberta'],localNote:'A Calgary-focused planning page for Somali Muslims organizing a small-group Umrah journey.',travelNote:'The first step is an expected travel period, not a confirmed flight.'},

  {slug:'melbourne',city:'Melbourne',country:'Australia',countryCode:'Australia',airport:'MEL',title:'Umrah from Melbourne for Somali Muslims',description:'Plan a premium small-group Umrah journey from Melbourne for Somali Muslims with transparent packages and personal support.',areas:['Melbourne','Greater Melbourne','Victoria'],localNote:'A Melbourne starting point for Somali Muslims in Victoria planning Umrah together.',travelNote:'Start with your group and expected travel period; final travel details follow the request.'},
  {slug:'sydney',city:'Sydney',country:'Australia',countryCode:'Australia',airport:'SYD',title:'Umrah from Sydney for Somali Muslims',description:'Plan a premium small-group Umrah journey from Sydney for Somali Muslims with transparent packages and personal support.',areas:['Sydney','Greater Sydney','New South Wales'],localNote:'A Sydney-focused planning page for Somali Muslims arranging a premium small-group Umrah journey.',travelNote:'An expected travel period is enough to begin planning.'},
  {slug:'brisbane',city:'Brisbane',country:'Australia',countryCode:'Australia',airport:'BNE',title:'Umrah from Brisbane for Somali Muslims',description:'Plan a premium small-group Umrah journey from Brisbane for Somali Muslims with transparent packages and personal support.',areas:['Brisbane','Greater Brisbane','Queensland'],localNote:'A Brisbane planning page for Somali Muslims in Queensland who want to arrange Umrah in a small group.',travelNote:'Start with your expected travel period and group size; confirmed flight details can follow.'},

  {slug:'oslo',city:'Oslo',country:'Norway',countryCode:'Norway',airport:'OSL',title:'Umrah from Oslo for Somali Muslims',description:'Plan a premium small-group Umrah journey from Oslo for Somali Muslims with transparent packages and personal support.',areas:['Oslo','Greater Oslo','Eastern Norway'],localNote:'A dedicated Oslo planning page for Norwegian-Somali families and friends arranging Umrah together.',travelNote:'Begin with an expected travel period and guest count.'},
  {slug:'helsinki',city:'Helsinki',country:'Finland',countryCode:'Finland',airport:'HEL',title:'Umrah from Helsinki for Somali Muslims',description:'Plan a premium small-group Umrah journey from Helsinki for Somali Muslims with transparent packages and personal support.',areas:['Helsinki','Espoo','Vantaa','Uusimaa'],localNote:'A Helsinki-area planning page for Somali Muslims in Finland arranging a small-group Umrah journey.',travelNote:'You can start with an expected period without confirmed flights.'}
];

export const getCitySeo=(slug:string)=>CITY_SEO.find(x=>x.slug===slug);
export const CITY_SLUGS = new Set(CITY_SEO.map(x=>x.slug));
