export type CitySeo={slug:string;city:string;country:string;countryCode:string;airport?:string;title:string;description:string;areas:string[];planningNote:string};
export const CITY_SEO:CitySeo[]=[
{slug:'london',city:'London',country:'United Kingdom',countryCode:'UK',title:'Umrah from London for Somali Muslims',description:'Plan a premium small-group Umrah journey from London for Somali Muslims with clear pricing, 5–8 guest groups and personal support.',areas:['London','Brent','Newham','Tower Hamlets'],planningNote:'For London groups, start by agreeing on one expected travel period across the household or group. We can then coordinate the departure details and final itinerary with you.'},
{slug:'birmingham',city:'Birmingham',country:'United Kingdom',countryCode:'UK',title:'Umrah from Birmingham for Somali Muslims',description:'Plan a premium small-group Umrah journey from Birmingham for Somali Muslims with transparent packages and personal support.',areas:['Birmingham'],planningNote:'For Birmingham groups, the first useful step is to align the group on guest count and an expected travel period before final transport and flight details are confirmed.'},
{slug:'manchester',city:'Manchester',country:'United Kingdom',countryCode:'UK',title:'Umrah from Manchester for Somali Muslims',description:'Plan a premium small-group Umrah journey from Manchester for Somali Muslims with transparent packages and personal support.',areas:['Manchester'],planningNote:'Manchester groups can begin with a shared travel window rather than a fixed flight date. This keeps planning flexible while the final itinerary is being coordinated.'},
{slug:'leicester',city:'Leicester',country:'United Kingdom',countryCode:'UK',title:'Umrah from Leicester for Somali Muslims',description:'Plan a premium small-group Umrah journey from Leicester for Somali Muslims with transparent packages and personal support.',areas:['Leicester'],planningNote:'For Leicester-based families and friends, agreeing on the group size and expected month first makes it easier to coordinate the journey together.'},
{slug:'bristol',city:'Bristol',country:'United Kingdom',countryCode:'UK',title:'Umrah from Bristol for Somali Muslims',description:'Plan a premium small-group Umrah journey from Bristol for Somali Muslims with transparent packages and personal support.',areas:['Bristol'],planningNote:'Bristol groups can request a journey using an expected travel period. Departure arrangements are then reviewed with the group before anything is confirmed.'},
{slug:'cardiff',city:'Cardiff',country:'United Kingdom',countryCode:'UK',title:'Umrah from Cardiff for Somali Muslims',description:'Plan a premium small-group Umrah journey from Cardiff for Somali Muslims with transparent packages and personal support.',areas:['Cardiff'],planningNote:'For Cardiff groups, share the preferred travel window and guest count first. The team can then work through the practical departure details with you.'},
{slug:'minneapolis',city:'Minneapolis',country:'United States',countryCode:'USA',title:'Umrah from Minneapolis for Somali Muslims',description:'Plan a premium small-group Umrah journey from Minneapolis for Somali Muslims with clear pricing, 5–8 guest groups and personal support.',areas:['Minneapolis','Twin Cities'],airport:'MSP',planningNote:'Minneapolis groups can plan together around the Twin Cities and use the expected travel period to coordinate guests before final departure details are confirmed.'},
{slug:'saint-paul',city:'Saint Paul',country:'United States',countryCode:'USA',title:'Umrah from Saint Paul for Somali Muslims',description:'Plan a premium small-group Umrah journey from Saint Paul for Somali Muslims with transparent packages and personal support.',areas:['Saint Paul','Twin Cities'],airport:'MSP',planningNote:'Saint Paul groups can coordinate as one Twin Cities group. Begin with the expected travel period and guest count, then confirm the practical departure arrangements.'},
{slug:'columbus',city:'Columbus',country:'United States',countryCode:'USA',title:'Umrah from Columbus for Somali Muslims',description:'Plan a premium small-group Umrah journey from Columbus for Somali Muslims with transparent packages and personal support.',areas:['Columbus','Central Ohio'],airport:'CMH',planningNote:'Columbus travelers can begin with a shared travel window and group size. Flight and departure details are handled separately once the journey plan is being finalized.'},
{slug:'seattle',city:'Seattle',country:'United States',countryCode:'USA',title:'Umrah from Seattle for Somali Muslims',description:'Plan a premium small-group Umrah journey from Seattle for Somali Muslims with transparent packages and personal support.',areas:['Seattle','Puget Sound'],airport:'SEA',planningNote:'Seattle-area groups can use one expected travel period to coordinate family members and friends before the final departure arrangements are confirmed.'},
{slug:'washington-dc',city:'Washington, DC',country:'United States',countryCode:'USA',title:'Umrah from Washington, DC for Somali Muslims',description:'Plan a premium small-group Umrah journey from Washington, DC for Somali Muslims with transparent packages and personal support.',areas:['Washington, DC','Northern Virginia','Maryland'],airport:'DCA / IAD',planningNote:'For groups across the DC, Northern Virginia and Maryland area, agreeing on a common travel window helps keep the group together while final departure details are coordinated.'},
{slug:'toronto',city:'Toronto',country:'Canada',countryCode:'Canada',title:'Umrah from Toronto for Somali Muslims',description:'Plan a premium small-group Umrah journey from Toronto for Somali Muslims with clear pricing, 5–8 guest groups and personal support.',areas:['Toronto','Greater Toronto Area'],airport:'YYZ',planningNote:'Toronto groups can organize around a shared expected travel period and guest list first, then work with the team on the final departure and itinerary details.'},
{slug:'edmonton',city:'Edmonton',country:'Canada',countryCode:'Canada',title:'Umrah from Edmonton for Somali Muslims',description:'Plan a premium small-group Umrah journey from Edmonton for Somali Muslims with transparent packages and personal support.',areas:['Edmonton'],airport:'YEG',planningNote:'Edmonton travelers can submit an expected month or date without having a confirmed flight. The final departure details are coordinated as the itinerary develops.'},
{slug:'calgary',city:'Calgary',country:'Canada',countryCode:'Canada',title:'Umrah from Calgary for Somali Muslims',description:'Plan a premium small-group Umrah journey from Calgary for Somali Muslims with transparent packages and personal support.',areas:['Calgary'],airport:'YYC',planningNote:'For Calgary groups, begin with the people traveling and their expected period. This gives the team a clear basis for coordinating the rest of the journey.'},
{slug:'ottawa',city:'Ottawa',country:'Canada',countryCode:'Canada',title:'Umrah from Ottawa for Somali Muslims',description:'Plan a premium small-group Umrah journey from Ottawa for Somali Muslims with transparent packages and personal support.',areas:['Ottawa'],airport:'YOW',planningNote:'Ottawa groups can start with a flexible travel period and a confirmed guest count. Departure and itinerary details are handled during the planning conversation.'},
{slug:'melbourne',city:'Melbourne',country:'Australia',countryCode:'Australia',title:'Umrah from Melbourne for Somali Muslims',description:'Plan a premium small-group Umrah journey from Melbourne for Somali Muslims with transparent packages and personal support.',areas:['Melbourne','Greater Melbourne'],airport:'MEL',planningNote:'Melbourne groups can begin months ahead with an expected travel period, giving families time to coordinate availability before the final itinerary is confirmed.'},
{slug:'sydney',city:'Sydney',country:'Australia',countryCode:'Australia',title:'Umrah from Sydney for Somali Muslims',description:'Plan a premium small-group Umrah journey from Sydney for Somali Muslims with transparent packages and personal support.',areas:['Sydney','Greater Sydney'],airport:'SYD',planningNote:'Sydney groups can first align on the expected travel period and guest list. The team then works through the final departure and journey arrangements with the group.'},
{slug:'brisbane',city:'Brisbane',country:'Australia',countryCode:'Australia',title:'Umrah from Brisbane for Somali Muslims',description:'Plan a premium small-group Umrah journey from Brisbane for Somali Muslims with transparent packages and personal support.',areas:['Brisbane'],airport:'BNE',planningNote:'Brisbane travelers can request the journey using an expected period instead of a confirmed flight date, keeping the planning process flexible at the start.'},
{slug:'sheffield',city:'Sheffield',country:'United Kingdom',countryCode:'UK',title:'Umrah from Sheffield for Somali Muslims',description:'Plan a premium small-group Umrah journey from Sheffield for Somali Muslims with transparent packages and personal support.',areas:['Sheffield','South Yorkshire'],airport:'MAN / LBA',planningNote:'Sheffield groups can start with guest count and expected travel period. The team can then review practical departure options before the final itinerary is confirmed.'},
{slug:'san-diego',city:'San Diego',country:'United States',countryCode:'USA',title:'Umrah from San Diego for Somali Muslims',description:'Plan a premium small-group Umrah journey from San Diego for Somali Muslims with transparent packages and personal support.',areas:['San Diego','Southern California'],airport:'SAN',planningNote:'San Diego groups can coordinate around one expected travel window and then review departure details as part of the final planning conversation.'},
{slug:'atlanta',city:'Atlanta',country:'United States',countryCode:'USA',title:'Umrah from Atlanta for Somali Muslims',description:'Plan a premium small-group Umrah journey from Atlanta for Somali Muslims with transparent packages and personal support.',areas:['Atlanta','Metro Atlanta'],airport:'ATL',planningNote:'Atlanta travelers can begin by gathering the group and choosing an expected period. Flight and departure details are confirmed separately once the itinerary is ready.'},
{slug:'oslo',city:'Oslo',country:'Norway',countryCode:'Norway',title:'Umrah from Oslo for Somali Muslims',description:'Plan a premium small-group Umrah journey from Oslo for Somali Muslims with transparent packages and personal support.',areas:['Oslo','Greater Oslo'],airport:'OSL',planningNote:'Oslo groups can start with an expected travel period and group size, then coordinate the final departure arrangements directly with the team.'},
{slug:'helsinki',city:'Helsinki',country:'Finland',countryCode:'Finland',title:'Umrah from Helsinki for Somali Muslims',description:'Plan a premium small-group Umrah journey from Helsinki for Somali Muslims with transparent packages and personal support.',areas:['Helsinki','Espoo','Vantaa'],airport:'HEL',planningNote:'Helsinki-area groups can use a flexible expected travel period to begin planning, with final departure and itinerary details confirmed later.'}
];
export const getCitySeo=(slug:string)=>CITY_SEO.find(x=>x.slug===slug);