export type CitySeo={slug:string;city:string;country:string;countryCode:string;airport?:string;title:string;description:string;areas:string[];localPlanning:string};

export const CITY_SEO:CitySeo[]=[
{slug:'london',city:'London',country:'United Kingdom',countryCode:'UK',title:'Umrah from London for Somali Muslims',description:'Plan a premium small-group Umrah journey from London for Somali Muslims with clear pricing, 5–8 guest groups and personal support.',areas:['London','Brent','Newham','Tower Hamlets'],airport:'LHR / LGW',localPlanning:'For London groups, planning can start around the city and nearby Somali community areas; the final international airport and flight are confirmed separately.'},
{slug:'birmingham',city:'Birmingham',country:'United Kingdom',countryCode:'UK',title:'Umrah from Birmingham for Somali Muslims',description:'Plan a premium small-group Umrah journey from Birmingham for Somali Muslims with transparent packages and personal support.',areas:['Birmingham','West Midlands'],airport:'BHX',localPlanning:'Birmingham groups can begin with a shared guest list and expected travel period, then confirm the departure airport and flights once the itinerary is reviewed.'},
{slug:'manchester',city:'Manchester',country:'United Kingdom',countryCode:'UK',title:'Umrah from Manchester for Somali Muslims',description:'Plan a premium small-group Umrah journey from Manchester for Somali Muslims with transparent packages and personal support.',areas:['Manchester','Greater Manchester'],airport:'MAN',localPlanning:'Manchester-area groups can coordinate one expected travel period even when guests live across Greater Manchester; flight details are confirmed later.'},
{slug:'leicester',city:'Leicester',country:'United Kingdom',countryCode:'UK',title:'Umrah from Leicester for Somali Muslims',description:'Plan a premium small-group Umrah journey from Leicester for Somali Muslims with transparent packages and personal support.',areas:['Leicester','Leicestershire'],airport:'EMA / BHX',localPlanning:'Leicester groups can share their preferred travel period first, with departure planning considered around East Midlands or another suitable airport.'},
{slug:'bristol',city:'Bristol',country:'United Kingdom',countryCode:'UK',title:'Umrah from Bristol for Somali Muslims',description:'Plan a premium small-group Umrah journey from Bristol for Somali Muslims with transparent packages and personal support.',areas:['Bristol','South West England'],airport:'BRS',localPlanning:'Bristol-area guests can start with the group size and expected period; the final flight and airport choice is handled within the confirmed itinerary.'},
{slug:'cardiff',city:'Cardiff',country:'United Kingdom',countryCode:'UK',title:'Umrah from Cardiff for Somali Muslims',description:'Plan a premium small-group Umrah journey from Cardiff for Somali Muslims with transparent packages and personal support.',areas:['Cardiff','South Wales'],airport:'CWL / BRS',localPlanning:'Cardiff and South Wales groups can request a journey before flights are finalized, with Cardiff or another suitable departure airport considered during planning.'},
{slug:'minneapolis',city:'Minneapolis',country:'United States',countryCode:'USA',title:'Umrah from Minneapolis for Somali Muslims',description:'Plan a premium small-group Umrah journey from Minneapolis for Somali Muslims with clear pricing, 5–8 guest groups and personal support.',areas:['Minneapolis','Twin Cities'],airport:'MSP',localPlanning:'For Minneapolis–Saint Paul groups, MSP provides a natural starting point for departure planning while the final international routing is confirmed separately.'},
{slug:'saint-paul',city:'Saint Paul',country:'United States',countryCode:'USA',title:'Umrah from Saint Paul for Somali Muslims',description:'Plan a premium small-group Umrah journey from Saint Paul for Somali Muslims with transparent packages and personal support.',areas:['Saint Paul','Twin Cities'],airport:'MSP',localPlanning:'Saint Paul groups can coordinate together with Minneapolis-area guests and use MSP as the departure reference while final flights remain separate from the package.'},
{slug:'columbus',city:'Columbus',country:'United States',countryCode:'USA',title:'Umrah from Columbus for Somali Muslims',description:'Plan a premium small-group Umrah journey from Columbus for Somali Muslims with transparent packages and personal support.',areas:['Columbus','Central Ohio'],airport:'CMH',localPlanning:'Columbus groups can begin with the guest count and expected period, using CMH as the local departure reference before final flight confirmation.'},
{slug:'seattle',city:'Seattle',country:'United States',countryCode:'USA',title:'Umrah from Seattle for Somali Muslims',description:'Plan a premium small-group Umrah journey from Seattle for Somali Muslims with transparent packages and personal support.',areas:['Seattle','Puget Sound'],airport:'SEA',localPlanning:'Seattle-area groups can organize the journey around a shared period and use SEA as the local departure reference; international flights are confirmed separately.'},
{slug:'washington-dc',city:'Washington, DC',country:'United States',countryCode:'USA',title:'Umrah from Washington, DC for Somali Muslims',description:'Plan a premium small-group Umrah journey from Washington, DC for Somali Muslims with transparent packages and personal support.',areas:['Washington, DC','Northern Virginia','Maryland'],airport:'DCA / IAD',localPlanning:'Groups around Washington, DC, Northern Virginia and Maryland can coordinate one expected period while the final airport and international routing are confirmed later.'},
{slug:'toronto',city:'Toronto',country:'Canada',countryCode:'Canada',title:'Umrah from Toronto for Somali Muslims',description:'Plan a premium small-group Umrah journey from Toronto for Somali Muslims with clear pricing, 5–8 guest groups and personal support.',areas:['Toronto','Greater Toronto Area'],airport:'YYZ',localPlanning:'Toronto-area groups can start with their preferred period and guest list, with YYZ used as the main departure reference when flights are later confirmed.'},
{slug:'edmonton',city:'Edmonton',country:'Canada',countryCode:'Canada',title:'Umrah from Edmonton for Somali Muslims',description:'Plan a premium small-group Umrah journey from Edmonton for Somali Muslims with transparent packages and personal support.',areas:['Edmonton','Alberta'],airport:'YEG',localPlanning:'Edmonton groups can submit an expected travel period before choosing final flights, with YEG as the local departure reference.'},
{slug:'calgary',city:'Calgary',country:'Canada',countryCode:'Canada',title:'Umrah from Calgary for Somali Muslims',description:'Plan a premium small-group Umrah journey from Calgary for Somali Muslims with transparent packages and personal support.',areas:['Calgary','Alberta'],airport:'YYC',localPlanning:'Calgary groups can coordinate the people and travel period first, then confirm the international departure details around YYC.'},
{slug:'ottawa',city:'Ottawa',country:'Canada',countryCode:'Canada',title:'Umrah from Ottawa for Somali Muslims',description:'Plan a premium small-group Umrah journey from Ottawa for Somali Muslims with transparent packages and personal support.',areas:['Ottawa','National Capital Region'],airport:'YOW',localPlanning:'Ottawa-area groups can start with an expected period and guest count; the final airport and flight routing is confirmed as part of the itinerary.'},
{slug:'melbourne',city:'Melbourne',country:'Australia',countryCode:'Australia',title:'Umrah from Melbourne for Somali Muslims',description:'Plan a premium small-group Umrah journey from Melbourne for Somali Muslims with transparent packages and personal support.',areas:['Melbourne','Greater Melbourne'],airport:'MEL',localPlanning:'Melbourne groups can begin planning around MEL and a shared expected period, with the final international flight confirmed separately.'},
{slug:'sydney',city:'Sydney',country:'Australia',countryCode:'Australia',title:'Umrah from Sydney for Somali Muslims',description:'Plan a premium small-group Umrah journey from Sydney for Somali Muslims with transparent packages and personal support.',areas:['Sydney','Greater Sydney'],airport:'SYD',localPlanning:'Sydney-area groups can coordinate a shared travel period and use SYD as the departure reference before final flight arrangements are confirmed.'},
{slug:'brisbane',city:'Brisbane',country:'Australia',countryCode:'Australia',title:'Umrah from Brisbane for Somali Muslims',description:'Plan a premium small-group Umrah journey from Brisbane for Somali Muslims with transparent packages and personal support.',areas:['Brisbane','South East Queensland'],airport:'BNE',localPlanning:'Brisbane groups can start with their guest count and expected period, then finalize international departure details around BNE.'},
{slug:'sheffield',city:'Sheffield',country:'United Kingdom',countryCode:'UK',title:'Umrah from Sheffield for Somali Muslims',description:'Plan a premium small-group Umrah journey from Sheffield for Somali Muslims with transparent packages and personal support.',areas:['Sheffield','South Yorkshire'],airport:'MAN / LBA',localPlanning:'Sheffield and South Yorkshire groups can plan around a shared period while Manchester or Leeds Bradford can be considered for the final departure.'},
{slug:'san-diego',city:'San Diego',country:'United States',countryCode:'USA',title:'Umrah from San Diego for Somali Muslims',description:'Plan a premium small-group Umrah journey from San Diego for Somali Muslims with transparent packages and personal support.',areas:['San Diego','Southern California'],airport:'SAN',localPlanning:'San Diego groups can begin with the expected period and local departure reference at SAN; final international routing is confirmed separately.'},
{slug:'atlanta',city:'Atlanta',country:'United States',countryCode:'USA',title:'Umrah from Atlanta for Somali Muslims',description:'Plan a premium small-group Umrah journey from Atlanta for Somali Muslims with transparent packages and personal support.',areas:['Atlanta','Metro Atlanta'],airport:'ATL',localPlanning:'Atlanta-area groups can organize guests and timing first, with ATL as the local departure reference when the final flights are confirmed.'},
{slug:'oslo',city:'Oslo',country:'Norway',countryCode:'Norway',title:'Umrah from Oslo for Somali Muslims',description:'Plan a premium small-group Umrah journey from Oslo for Somali Muslims with transparent packages and personal support.',areas:['Oslo','Greater Oslo'],airport:'OSL',localPlanning:'Oslo groups can submit an expected travel period and group size first, then coordinate the final departure details around OSL.'},
{slug:'helsinki',city:'Helsinki',country:'Finland',countryCode:'Finland',title:'Umrah from Helsinki for Somali Muslims',description:'Plan a premium small-group Umrah journey from Helsinki for Somali Muslims with transparent packages and personal support.',areas:['Helsinki','Espoo','Vantaa'],airport:'HEL',localPlanning:'Helsinki-area groups can begin with the guest list and expected period, using HEL as the local departure reference before final flight confirmation.'}
];

export const getCitySeo=(slug:string)=>CITY_SEO.find(x=>x.slug===slug);
