import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {cookies} from 'next/headers';
import {packages} from '@/lib/site';
import {defaultLocale,isLocale,pageCopy} from '@/lib/i18n';
import type {Metadata} from 'next';
const hero='https://images.pexels.com/photos/32839113/pexels-photo-32839113.jpeg?auto=compress&cs=tinysrgb&w=2200';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}): Promise<Metadata> {
  const {slug}=await params;
  const p=packages[slug as 'signature'|'elite'];
  if(!p) return {};
  const title=`${p.name} Umrah Journey — ${p.price.toLocaleString()} per guest | ALHARAMAIN ELITE`;
  const description=slug==='elite'
    ? 'ELITE is a 10-day / 9-night premium Umrah journey at $2,500 per guest, designed for small groups.'
    : 'SIGNATURE is a 10-day / 9-night premium Umrah journey at $2,000 per guest, designed for small groups.';
  return { title, description, alternates:{canonical:`/packages/${slug}`}, openGraph:{title,description,type:'website'} };
}

const labels={en:{included:'Included',not:'Not included',ready:'Ready when you are',request:'Request this journey',compare:'Compare journeys',duration:'10 days / 9 nights',flights:'International flights are not included',features:['Premium hotels in Makkah & Madinah','Daily breakfast','Private transportation as confirmed in your itinerary','Guided Makkah & Madinah ziyarat','Jeddah experience where included','SIM card with internet','Journey support'],eliteExtra:['Haramain Train travel where applicable'],notList:['International flights','Personal expenses','Any service not expressly confirmed in your final itinerary']},so:{included:'Waxa ku jira',not:'Kuma jiraan',ready:'Markaad diyaar tahay',request:'Codso safarkan',compare:'Is barbar dhig safarrada',duration:'10 maalmood / 9 habeen',flights:'Duulimaadyada caalamiga ah kuma jiraan',features:['Hoteello heer sare ah oo ku yaal Makkah iyo Madiinah','Quraac maalinle ah','Gaadiid gaar ah sida lagu xaqiijiyo jadwalkaaga','Ziyaraat hagitaan leh oo Makkah iyo Madiinah ah','Khibradda Jeddah marka ay ku jirto barnaamijka','SIM internet leh','Taageerada safarka'],eliteExtra:['Safarka Haramain Train marka uu ku habboon yahay'],notList:['Duulimaadyada caalamiga ah','Kharashaadka gaarka ah','Adeeg kasta oo aan si cad loogu xaqiijin jadwalkaaga']},ar:{included:'يشمل',not:'لا يشمل',ready:'عندما تكون مستعدًا',request:'اطلب هذه الرحلة',compare:'مقارنة الرحلات',duration:'10 أيام / 9 ليالٍ',flights:'الرحلات الدولية غير مشمولة',features:['فنادق راقية في مكة والمدينة','وجبة إفطار يومية','تنقلات خاصة وفق البرنامج المؤكد','زيارات بإرشاد في مكة والمدينة','تجربة جدة عند تضمينها في البرنامج','شريحة إنترنت','دعم ومساندة خلال الرحلة'],eliteExtra:['رحلة عبر قطار الحرمين حيث يناسب البرنامج'],notList:['الرحلات الدولية','المصاريف الشخصية','أي خدمة لم يتم تأكيدها صراحة في البرنامج النهائي']}};
export default async function PackagePage({params}:{params:Promise<{slug:string}>}){
const {slug}=await params; const p=packages[slug as 'signature'|'elite']; if(!p)notFound();
const raw=(await cookies()).get('he_locale')?.value; const l=isLocale(raw)?raw:defaultLocale; const t=labels[l]; const base=pageCopy[l].packages;
const positioning=l==='ar'?(slug==='elite'?'مستوى أعلى من الإقامة والتجربة، مع قطار الحرمين حيث يناسب البرنامج.':'راحة راقية وتجربة عمرة متكاملة، مرتبة بعناية للمجموعات الصغيرة.'):l==='so'?(slug==='elite'?'Heer sare oo hoy iyo khibrad ah, oo ay ku jirto Haramain Train marka uu ku habboon yahay.':'Raaxo heer sare ah iyo safar Cumro oo dhammaystiran, si taxaddar leh loogu diyaariyay kooxo yaryar.'):p.positioning;
const list=slug==='elite'?[...t.features,...t.eliteExtra]:t.features;
return <div><section className='relative overflow-hidden bg-forest text-white'><Image src={hero} alt='Makkah' fill priority className='object-cover opacity-30' sizes='100vw'/><div className='absolute inset-0 bg-forest/80'/><div className='container relative max-w-5xl py-28'><div className='eyebrow'>{p.name}</div><h1 className='serif mt-4 text-7xl'>{p.name}</h1><div className='mt-6 flex items-end gap-3'><span className='serif text-6xl text-gold'>{'$'+p.price.toLocaleString()}</span><span className='pb-2 text-white/60'>{l==='ar'?'/ ضيف':l==='so'?'/ marti':'/ guest'}</span></div><p className='mt-6 max-w-2xl text-lg leading-8 text-white/75'>{positioning}</p><p className='mt-3 text-sm text-white/55'>{t.duration} · {t.flights}</p></div></section>
<section className='section'><div className='container grid gap-12 md:grid-cols-3'><div className='md:col-span-2'><h2 className='serif text-4xl text-forest'>{t.included}</h2><div className='mt-7 grid gap-3 sm:grid-cols-2'>{list.map(f=><div key={f} className='border-b border-forest/10 py-4 text-forest/75'>{f}</div>)}</div><h2 className='serif mt-14 text-4xl text-forest'>{t.not}</h2><div className='mt-7 grid gap-3'>{t.notList.map(f=><div key={f} className='border-b border-forest/10 py-4 text-forest/65'>{f}</div>)}</div></div>
<aside className='card h-fit p-7'><div className='eyebrow'>{t.ready}</div><p className='mt-4 leading-7 text-forest/65'>{l==='ar'?'لا تحتاج إلى تاريخ رحلة مؤكد للبدء. شاركنا الفترة المتوقعة وسيتواصل معك فريقنا.':l==='so'?'Uma baahnid taariikh duulimaad la xaqiijiyay. Sheeg muddada aad filayso, kooxdayaduna way kula soo xiriiri doontaa.':'You do not need a confirmed flight date to start. Share your expected travel date or period and our team will contact you personally. There is no need to have your international flight booked yet.'}</p><Link href={'/request-journey?package='+slug} className='btn btn-primary mt-6 w-full'>{t.request}</Link><Link href='/packages' className='btn btn-outline mt-3 w-full'>{t.compare}</Link></aside></div></section></div>}