'use client';
import {useState} from 'react';
type D={id:string;departure_date:string;duration_nights:number;group_size:number;max_groups:number|null;status:string;public_label:string|null;notes:string|null};
const rolesNote='A blank maximum means the departure can accept more groups until you close it manually.';
export function DepartureManager({initial}:{initial:D[]}){
 const ar=typeof document!=='undefined'&&document.cookie.includes('he_locale=ar');const [rows,setRows]=useState(initial);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const [dates,setDates]=useState<Record<string,string>>({});
 const save=async(payload:any,method:'POST'|'PATCH'|'DELETE')=>{setBusy(true);setMsg('');try{const r=await fetch('/api/admin/departures',{method,headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.error||'Could not save departure.');return false}setMsg(ar?'تم الحفظ بنجاح.':'Saved successfully.');return true}catch{setMsg(ar?'تعذر الاتصال. حاول مجددًا.':'Connection failed. Please try again.');return false}finally{setBusy(false)}};
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const ok=await save({departure_date:f.get('date'),duration_nights:Number(f.get('nights')||9),group_size:Number(f.get('size')||8),max_groups:f.get('max_groups'),public_label:f.get('label')||null,notes:f.get('notes')||null},'POST');if(ok)location.reload()};
 const setStatus=async(id:string,status:string)=>{const ok=await save({id,status},'PATCH');if(ok)setRows(x=>x.map(r=>r.id===id?{...r,status}:r))};
 const changeDate=async(r:D)=>{const departure_date=dates[r.id]||r.departure_date;if(departure_date===r.departure_date)return;const ok=await save({id:r.id,departure_date},'PATCH');if(ok)location.reload()};
 const remove=async(r:D)=>{if(!window.confirm(ar?'هل تريد حذف هذا الموعد؟ لا يمكن حذف موعد مرتبط بحجوزات.':'Delete this departure? Dates linked to bookings cannot be deleted.'))return;const ok=await save({id:r.id},'DELETE');if(ok)setRows(x=>x.filter(v=>v.id!==r.id))};
 return <div className="mt-7"><form onSubmit={create} className="card grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-6"><input name="date" type="date" required/><input name="nights" type="number" min="1" max="30" defaultValue="9" placeholder="Nights"/><input name="size" type="number" min="1" max="8" defaultValue="8" placeholder="Group size"/><input name="max_groups" type="number" min="1" placeholder="Max groups"/><input name="label" placeholder="Public label"/><button disabled={busy} className="btn btn-primary">{busy?'Saving…':'Add departure'}</button><input name="notes" placeholder={rolesNote} className="sm:col-span-2 lg:col-span-6"/>{msg&&<div role="status" className="text-sm text-forest/60 sm:col-span-2 lg:col-span-6">{msg}</div>}</form>
 <div className="card mt-6 overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="border-b border-forest/10 bg-[#faf8f2]"><tr>{['Departure date','Duration','Group size','Max groups','Status','Public booking','Date controls'].map(x=><th key={x} className="px-4 py-4">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-forest/8 last:border-0"><td className="px-4 py-4"><div className="font-semibold">{r.public_label||r.departure_date}</div><input aria-label={'Edit date '+r.departure_date} type="date" value={dates[r.id]??r.departure_date} onChange={e=>setDates(x=>({...x,[r.id]:e.target.value}))} className="mt-2 max-w-[170px] text-xs"/></td><td className="px-4 py-4">{r.duration_nights} nights</td><td className="px-4 py-4">{r.group_size}</td><td className="px-4 py-4">{r.max_groups??'Unlimited'}</td><td className="px-4 py-4"><span className="rounded-full bg-[#f7f3ea] px-3 py-1 text-xs font-semibold">{r.status}</span></td><td className="px-4 py-4">{r.status==='OPEN'?<button disabled={busy} onClick={()=>setStatus(r.id,'CLOSED')} className="btn btn-outline">Close date</button>:<button disabled={busy} onClick={()=>setStatus(r.id,'OPEN')} className="btn btn-primary">Open for more groups</button>}</td><td className="px-4 py-4"><div className="flex items-center gap-2"><button disabled={busy||!dates[r.id]||dates[r.id]===r.departure_date} onClick={()=>changeDate(r)} className="btn btn-outline">{ar?'استبدال التاريخ':'Replace date'}</button><button disabled={busy} onClick={()=>remove(r)} className="btn btn-outline !border-red-200 !text-red-700">{ar?'حذف':'Delete'}</button></div></td></tr>)}</tbody></table></div></div>
}