'use client';
import {useEffect,useMemo,useState} from 'react';

type Any=any;
const money=(n:number,c='USD')=>`${c} ${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const arText=(ar:boolean,en:string,arv:string)=>ar?arv:en;

export default function FinanceCenter({role}:{role:string}){
 const [d,setD]=useState<Any|null>(null);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState('');
 const ar=typeof document!=='undefined'&&document.cookie.includes('he_locale=ar');
 async function load(){setLoading(true);const r=await fetch('/api/admin/finance',{cache:'no-store'});const j=await r.json();if(r.ok)setD(j);else setMsg(j.error||'Unable to load finance data.');setLoading(false)}
 useEffect(()=>{load()},[]);
 async function post(body:Any){setMsg('');const r=await fetch('/api/admin/finance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setMsg(r.ok?ar?'تم الحفظ بنجاح.':'Saved successfully.':j.error||'Could not save.');if(r.ok)await load()}
 async function patch(body:Any){setMsg('');const r=await fetch('/api/admin/finance',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setMsg(r.ok?ar?'تم تحديث الحالة.':'Status updated.':j.error||'Could not update.');if(r.ok)await load()}
 const usd=(arr:Any[],field:string,status?:string)=>arr.filter(x=>(!status||x.status===status)&&String(x.currency||'USD').trim()==='USD').reduce((n,x)=>n+Number(x[field]||0),0);const usdStatuses=(arr:Any[],field:string,statuses:string[])=>arr.filter(x=>statuses.includes(String(x.status))&&String(x.currency||'USD').trim()==='USD').reduce((n,x)=>n+Number(x[field]||0),0);
 const revenue=useMemo(()=>d?usd(d.bookings,'total_amount'):0,[d]);const collected=useMemo(()=>d?usd(d.payments,'amount','RECEIVED'):0,[d]);const costs=useMemo(()=>d?(usd(d.costs,'amount')+usdStatuses(d.expenses,'amount',['APPROVED','PAID'])):0,[d]);const payroll=useMemo(()=>d?usd(d.payroll,'base_salary','PAID'):0,[d]);const bonuses=useMemo(()=>d?usd(d.bonuses,'amount','PAID'):0,[d]);const outstanding=Math.max(revenue-collected,0);const net=revenue-costs-payroll-bonuses;
 if(loading)return <div className="card p-8 text-center text-forest/55">{ar?'جارٍ تحميل المركز المالي…':'Loading Finance Center…'}</div>;
 if(!d)return <div className="card p-8">{msg}</div>;
 const profiles=d.profiles||[],bookings=d.bookings||[],groups=d.groups||[];
 const staffName=(id:string)=>profiles.find((p:Any)=>p.id===id)?.full_name||profiles.find((p:Any)=>p.id===id)?.role||id;
 return <div className="grid gap-6">
  {msg&&<div className="rounded-xl border border-gold/30 bg-[#fffaf0] p-4 text-sm text-forest">{msg}</div>}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
   {[[ar?'الإيرادات':'Revenue',money(revenue),''],[ar?'المحصّل':'Collected',money(collected),''],[ar?'المتبقي':'Outstanding',money(outstanding),''],[ar?'صافي النتيجة':'Net result',money(net),'']].map(([a,b],i)=><div key={i} className="card p-5"><div className="text-xs text-forest/50">{a}</div><div className="mt-2 text-2xl font-semibold text-forest">{b}</div></div>)}
  </div>
  <div className="grid gap-3 sm:grid-cols-3"><div className="card p-5"><div className="text-xs text-forest/50">{ar?'تكاليف الرحلات':'Journey costs'}</div><div className="mt-2 text-xl font-semibold">{money(usd(d.costs,'amount'))}</div></div><div className="card p-5"><div className="text-xs text-forest/50">{ar?'الرواتب المدفوعة':'Paid payroll'}</div><div className="mt-2 text-xl font-semibold">{money(payroll)}</div></div><div className="card p-5"><div className="text-xs text-forest/50">{ar?'المكافآت المدفوعة':'Paid bonuses'}</div><div className="mt-2 text-xl font-semibold">{money(bonuses)}</div></div></div>

  <section className="card p-5"><div className="eyebrow">{ar?'تكاليف الخدمات':'Service Cost Catalog'}</div><h2 className="serif mt-2 text-3xl text-forest">{ar?'الفنادق والنقل والقطار والفعاليات والمضيفون':'Hotels, transport, train, experiences & hosts'}</h2>
   {(role==='SUPER_ADMIN'||role==='ADMIN')&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({action:'catalog',name:f.get('name'),category:f.get('category'),unit:f.get('unit'),unit_cost:f.get('unit_cost'),currency:f.get('currency'),supplier_id:f.get('supplier_id')||null,notes:f.get('notes')});e.currentTarget.reset()}} className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
    <input name="name" required placeholder={ar?'اسم الخدمة':'Service name'}/><select name="category"><option value="HOTEL">HOTEL</option><option value="TRANSPORTATION">TRANSPORTATION</option><option value="TRAIN">TRAIN</option><option value="EXPERIENCE">EXPERIENCE</option><option value="HOST">HOST</option><option value="OTHER">OTHER</option></select><input name="unit" defaultValue="SERVICE" placeholder="Unit"/><input name="unit_cost" required type="number" min="0" step="0.01" placeholder={ar?'تكلفة الوحدة':'Unit cost'}/><select name="currency"><option>USD</option><option>SAR</option></select><select name="supplier_id"><option value="">{ar?'بدون مورد':'No supplier'}</option>{d.suppliers.map((s:Any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="notes" placeholder={ar?'ملاحظات':'Notes'} className="sm:col-span-2"/><button className="btn btn-primary">{ar?'إضافة تكلفة':'Add cost'}</button>
   </form>}
   <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr>{['Service','Category','Supplier','Unit','Cost','Currency','Active'].map(h=><th key={h} className="px-3 py-3 text-left">{h}</th>)}</tr></thead><tbody>{d.catalog.map((x:Any)=><tr key={x.id} className="border-t border-forest/8"><td className="px-3 py-3 font-semibold">{x.name}</td><td className="px-3 py-3">{x.category}</td><td className="px-3 py-3">{d.suppliers.find((s:Any)=>s.id===x.supplier_id)?.name||'—'}</td><td className="px-3 py-3">{x.unit}</td><td className="px-3 py-3">{Number(x.unit_cost).toLocaleString()}</td><td className="px-3 py-3">{x.currency}</td><td className="px-3 py-3">{x.active?'YES':'NO'}</td></tr>)}</tbody></table></div>
  </section>

  <section className="card p-5"><div className="eyebrow">{ar?'الموردون':'Suppliers'}</div><h2 className="serif mt-2 text-3xl text-forest">{ar?'دليل الموردين':'Supplier Directory'}</h2>
   {(role==='SUPER_ADMIN'||role==='ADMIN')&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({action:'supplier',name:f.get('name'),supplier_type:f.get('supplier_type'),contact_name:f.get('contact_name'),phone:f.get('phone'),email:f.get('email'),notes:f.get('notes')});e.currentTarget.reset()}} className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input name="name" required placeholder={ar?'اسم المورد':'Supplier name'}/><select name="supplier_type"><option>HOTEL</option><option>TRANSPORTATION</option><option>TRAIN</option><option>EXPERIENCE</option><option>HOST</option><option>OTHER</option></select><input name="contact_name" placeholder={ar?'اسم جهة الاتصال':'Contact name'}/><input name="phone" placeholder={ar?'الهاتف':'Phone'}/><input name="email" placeholder="Email"/><input name="notes" placeholder={ar?'ملاحظات':'Notes'} className="sm:col-span-2"/><button className="btn btn-primary">{ar?'إضافة مورد':'Add supplier'}</button></form>}
   <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{d.suppliers.map((s:Any)=><div key={s.id} className="rounded-xl bg-[#f7f3ea] p-4"><div className="font-semibold text-forest">{s.name}</div><div className="mt-1 text-xs text-forest/55">{s.supplier_type} · {s.phone||s.email||'—'}</div></div>)}</div>
  </section>

  <section className="card p-5"><div className="eyebrow">{ar?'تكاليف الرحلات':'Journey Costs'}</div><h2 className="serif mt-2 text-3xl text-forest">{ar?'تسجيل التكلفة الفعلية':'Record Journey Costs'}</h2>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({action:'journey_cost',booking_id:f.get('booking_id')||null,group_id:f.get('group_id')||null,category:f.get('category'),description:f.get('description'),quantity:f.get('quantity'),amount:f.get('amount'),currency:f.get('currency'),date:f.get('date'),supplier_id:f.get('supplier_id')||null,notes:f.get('notes')});e.currentTarget.reset()}} className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
    <select name="booking_id"><option value="">{ar?'بدون حجز':'No booking'}</option>{bookings.map((b:Any)=><option key={b.id} value={b.id}>{b.booking_id}</option>)}</select><select name="group_id"><option value="">{ar?'بدون مجموعة':'No group'}</option>{groups.map((g:Any)=><option key={g.id} value={g.id}>{g.group_id}</option>)}</select><select name="category"><option>HOTEL</option><option>TRANSPORTATION</option><option>TRAIN</option><option>EXPERIENCE</option><option>HOST</option><option>OTHER</option></select><input name="description" required placeholder={ar?'وصف التكلفة':'Description'}/><input name="quantity" type="number" step="0.01" min="0.01" defaultValue="1"/><input name="amount" required type="number" step="0.01" min="0" placeholder={ar?'المبلغ':'Amount'}/><select name="currency"><option>USD</option><option>SAR</option></select><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><select name="supplier_id"><option value="">{ar?'بدون مورد':'No supplier'}</option>{d.suppliers.map((s:Any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="notes" placeholder={ar?'ملاحظات':'Notes'} className="sm:col-span-2"/><button className="btn btn-primary">{ar?'تسجيل التكلفة':'Record cost'}</button>
   </form>
   <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr>{['Date','Booking','Category','Description','Supplier','Amount'].map(h=><th key={h} className="px-3 py-3 text-left">{h}</th>)}</tr></thead><tbody>{d.costs.slice(0,30).map((x:Any)=><tr key={x.id} className="border-t border-forest/8"><td className="px-3 py-3">{x.date}</td><td className="px-3 py-3">{bookings.find((b:Any)=>b.id===x.booking_id)?.booking_id||'—'}</td><td className="px-3 py-3">{x.category}</td><td className="px-3 py-3">{x.description}</td><td className="px-3 py-3">{d.suppliers.find((s:Any)=>s.id===x.supplier_id)?.name||'—'}</td><td className="px-3 py-3">{money(Number(x.amount),x.currency)}</td></tr>)}</tbody></table></div>
  </section>

  <section className="card p-5"><div className="eyebrow">{ar?'الرواتب والمكافآت':'Payroll & Bonuses'}</div><h2 className="serif mt-2 text-3xl text-forest">{ar?'إدارة التعويضات':'Staff Compensation'}</h2>
   {role==='SUPER_ADMIN'&&<div className="mt-5 grid gap-6 lg:grid-cols-2">
    <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({action:'compensation',staff_id:f.get('staff_id'),base_salary:f.get('base_salary'),currency:f.get('currency'),pay_frequency:f.get('pay_frequency'),effective_from:f.get('effective_from'),notes:f.get('notes')})}} className="grid gap-3 rounded-xl bg-[#f7f3ea] p-4"><div className="font-semibold">{ar?'تحديد الراتب الأساسي':'Set base salary'}</div><select name="staff_id" required><option value="">{ar?'اختر الموظف':'Select staff'}</option>{profiles.map((p:Any)=><option key={p.id} value={p.id}>{p.full_name||p.role} · {p.role}</option>)}</select><input name="base_salary" required type="number" min="0" step="0.01" placeholder={ar?'الراتب':'Base salary'}/><select name="currency"><option>USD</option><option>SAR</option></select><select name="pay_frequency"><option>MONTHLY</option><option>WEEKLY</option><option>OTHER</option></select><input name="effective_from" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><input name="notes" placeholder={ar?'ملاحظات':'Notes'}/><button className="btn btn-primary">{ar?'حفظ الراتب':'Save salary'}</button></form>
    <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({action:'bonus',staff_id:f.get('staff_id'),amount:f.get('amount'),currency:f.get('currency'),bonus_date:f.get('bonus_date'),reason:f.get('reason'),notes:f.get('notes')});e.currentTarget.reset()}} className="grid gap-3 rounded-xl bg-[#f7f3ea] p-4"><div className="font-semibold">{ar?'مكافأة خاصة':'Special bonus'}</div><select name="staff_id" required><option value="">{ar?'اختر الموظف':'Select staff'}</option>{profiles.map((p:Any)=><option key={p.id} value={p.id}>{p.full_name||p.role}</option>)}</select><input name="amount" required type="number" min="0.01" step="0.01" placeholder={ar?'المكافأة':'Bonus amount'}/><select name="currency"><option>USD</option><option>SAR</option></select><input name="bonus_date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><input name="reason" required placeholder={ar?'سبب المكافأة':'Reason'}/><input name="notes" placeholder={ar?'ملاحظات':'Notes'}/><button className="btn btn-primary">{ar?'إضافة المكافأة':'Add bonus'}</button></form>
   </div>}
   <div className="mt-5 grid gap-3 md:grid-cols-2">{d.compensation.map((x:Any)=><div key={x.id} className="rounded-xl border border-forest/10 p-4"><div className="font-semibold">{staffName(x.staff_id)}</div><div className="mt-1 text-sm">{money(x.base_salary,x.currency)} · {x.pay_frequency}</div></div>)}</div>
  </section>

  <section className="card p-5"><div className="eyebrow">{ar?'الرواتب':'Payroll'}</div><h2 className="serif mt-2 text-3xl text-forest">{ar?'تسجيل صرف الرواتب':'Record Payroll Payment'}</h2>
   <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post({action:'payroll',staff_id:f.get('staff_id'),period_start:f.get('period_start'),period_end:f.get('period_end'),base_salary:f.get('base_salary'),bonus_amount:f.get('bonus_amount'),currency:f.get('currency'),status:f.get('status'),paid_date:f.get('paid_date'),reference:f.get('reference')})}} className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
    <select name="staff_id" required><option value="">{ar?'اختر الموظف':'Select staff'}</option>{profiles.map((p:Any)=><option key={p.id} value={p.id}>{p.full_name||p.role}</option>)}</select><input name="period_start" required type="date"/><input name="period_end" required type="date"/><input name="base_salary" required type="number" min="0" step="0.01" placeholder={ar?'الراتب':'Salary'}/><input name="bonus_amount" type="number" min="0" step="0.01" defaultValue="0" placeholder={ar?'المكافأة':'Bonus'}/><select name="currency"><option>USD</option><option>SAR</option></select><select name="status"><option>PENDING</option><option>PAID</option></select><input name="paid_date" type="date"/><input name="reference" placeholder={ar?'مرجع الدفع':'Payment reference'}/><button className="btn btn-primary">{ar?'تسجيل الرواتب':'Record payroll'}</button>
   </form>
   <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr>{['Staff','Period','Base','Bonus','Total','Status','Paid date'].map(h=><th key={h} className="px-3 py-3 text-left">{h}</th>)}</tr></thead><tbody>{d.payroll.map((x:Any)=><tr key={x.id} className="border-t border-forest/8"><td className="px-3 py-3">{staffName(x.staff_id)}</td><td className="px-3 py-3">{x.period_start} → {x.period_end}</td><td className="px-3 py-3">{money(x.base_salary,x.currency)}</td><td className="px-3 py-3">{money(x.bonus_amount,x.currency)}</td><td className="px-3 py-3 font-semibold">{money(x.total_amount,x.currency)}</td><td className="px-3 py-3">{x.status}</td><td className="px-3 py-3">{x.paid_date||'—'}</td></tr>)}</tbody></table></div>
  </section>

  <section className="card p-5"><div className="eyebrow">{ar?'المصروفات':'Expenses'}</div><h2 className="serif mt-2 text-3xl text-forest">{ar?'اعتماد ومتابعة المصروفات':'Expense Control'}</h2>
   <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr>{['Date','Category','Supplier','Amount','Booking','Status','Action'].map(h=><th key={h} className="px-3 py-3 text-left">{h}</th>)}</tr></thead><tbody>{d.expenses.slice(0,50).map((x:Any)=><tr key={x.id} className="border-t border-forest/8"><td className="px-3 py-3">{x.date}</td><td className="px-3 py-3">{x.category}</td><td className="px-3 py-3">{x.supplier||'—'}</td><td className="px-3 py-3">{money(x.amount,x.currency)}</td><td className="px-3 py-3">{bookings.find((b:Any)=>b.id===x.booking_id)?.booking_id||'—'}</td><td className="px-3 py-3">{x.status}</td><td className="px-3 py-3">{x.status==='PENDING'&&<span className="flex gap-2"><button className="btn btn-outline !px-3 !py-2 text-xs" onClick={()=>patch({action:'expense_status',id:x.id,status:'APPROVED'})}>{ar?'اعتماد':'Approve'}</button><button className="btn btn-outline !px-3 !py-2 text-xs" onClick={()=>patch({action:'expense_status',id:x.id,status:'REJECTED'})}>{ar?'رفض':'Reject'}</button></span>}{x.status==='APPROVED'&&<button className="btn btn-primary !px-3 !py-2 text-xs" onClick={()=>patch({action:'expense_status',id:x.id,status:'PAID'})}>{ar?'تم الدفع':'Mark paid'}</button>}</td></tr>)}</tbody></table></div>
  </section>

  <section className="card p-5"><div className="eyebrow">{ar?'المكافآت':'Bonuses'}</div><h2 className="serif mt-2 text-3xl text-forest">{ar?'المكافآت الخاصة':'Special Bonuses'}</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr>{['Staff','Date','Reason','Amount','Status','Action'].map(h=><th key={h} className="px-3 py-3 text-left">{h}</th>)}</tr></thead><tbody>{d.bonuses.map((x:Any)=><tr key={x.id} className="border-t border-forest/8"><td className="px-3 py-3">{staffName(x.staff_id)}</td><td className="px-3 py-3">{x.bonus_date}</td><td className="px-3 py-3">{x.reason}</td><td className="px-3 py-3">{money(x.amount,x.currency)}</td><td className="px-3 py-3">{x.status}</td><td className="px-3 py-3">{x.status==='APPROVED'&&<button className="btn btn-primary !px-3 !py-2 text-xs" onClick={()=>patch({action:'bonus_status',id:x.id,status:'PAID'})}>{ar?'صرف المكافأة':'Mark paid'}</button>}</td></tr>)}</tbody></table></div></section>
 </div>
}

// Finance Center v1: payments, service costs, suppliers, expenses, payroll and bonuses. Commission tracking and estimated-vs-actual are intentionally deferred.
