'use client';
import {useState} from 'react';
export function InfluencerPartnerDetail({partner,commissions,payouts,role}:{partner:any;commissions:any[];payouts:any[];role:string}){
 const[p,setP]=useState(partner);const[form,setForm]=useState({fullName:partner.full_name,email:partner.email,whatsapp:partner.whatsapp,country:partner.country,slug:partner.slug});const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 async function save(){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/influencer-partners',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:p.id,fullName:form.fullName,email:form.email,whatsapp:form.whatsapp,country:form.country,slug:form.slug})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to update partner.');setP(d.partner);setMsg('Saved.')}catch(e){setMsg(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 const sales=commissions.filter(c=>c.type==='COMMISSION').reduce((n,c)=>n+Number(c.amount)/0.05,0);const bookings=new Set(commissions.filter(c=>c.type==='COMMISSION').map(c=>c.booking_id)).size;const paid=payouts.filter(x=>x.status==='PAID').reduce((n,x)=>n+Number(x.amount),0);
 return <div className="grid gap-7"><div className="card p-7"><div className="eyebrow">Partner profile</div><div className="mt-5 grid gap-5 md:grid-cols-2">{[['Full name','fullName'],['Email','email'],['WhatsApp','whatsapp'],['Country','country'],['Referral slug','slug']].map(([label,key])=><label key={key}>{label}<input value={(form as any)[key]} disabled={key==='email'&&role!=='SUPER_ADMIN'} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} className="btn btn-primary" onClick={save}>Save changes</button>{msg&&<span className="self-center text-sm text-forest/55">{msg}</span>}</div></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Status',p.status],['Sales','$ '+sales.toLocaleString()],['Bookings',bookings],['Paid','$ '+paid.toLocaleString()]].map(([l,v])=><div className="card p-5" key={String(l)}><div className="eyebrow">{l}</div><div className="serif mt-2 text-3xl text-forest">{v}</div></div>)}</div>
 <div className="card overflow-x-auto"><div className="border-b border-forest/10 p-6"><div className="eyebrow">Commission history</div></div><table className="w-full min-w-[850px] text-sm"><thead><tr>{['Booking','Type','Amount','Status','Available'].map(h=><th key={h} className="px-4 py-4 text-left">{h}</th>)}</tr></thead><tbody>{commissions.map(c=><tr key={c.id} className="border-t border-forest/10"><td className="px-4 py-4">{c.booking_id||'—'}</td><td className="px-4 py-4">{c.type}</td><td className="px-4 py-4">{c.type==='RECOVERY'?'−':'+'}$ {Number(c.amount).toLocaleString()}</td><td className="px-4 py-4">{c.status}</td><td className="px-4 py-4">{new Date(c.available_at).toLocaleString('en-GB')}</td></tr>)}</tbody></table><div className="border-t border-forest/10 p-6"><div className="eyebrow">Payout history</div><div className="mt-4 grid gap-3">{payouts.map(x=><div key={x.id} className="flex justify-between border-b border-forest/10 py-3"><span>$ {Number(x.amount).toLocaleString()}</span><span>{x.status}</span></div>)}</div></div></div></div>;
}