'use client';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
export function InfluencerPartnersAdmin({initialRows,payouts,role}:{initialRows:any[];payouts:any[];role:string}){
 const router=useRouter();const[rows,setRows]=useState(initialRows);const[q,setQ]=useState('');const[country,setCountry]=useState('');const[status,setStatus]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 const[form,setForm]=useState({fullName:'',email:'',whatsapp:'',country:''});
 const filtered=useMemo(()=>rows.filter(r=>(!q||r.full_name.toLowerCase().includes(q.toLowerCase()))&&(!country||r.country===country)&&(!status||r.status===status)),[rows,q,country,status]);
 const countries=Array.from(new Set(rows.map(r=>r.country))).sort();
 async function add(){if(role!=='SUPER_ADMIN')return;setBusy(true);setMsg('');try{const r=await fetch('/api/admin/influencer-partners',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to add partner.');setMsg('Partner added. Temporary password: '+d.temporaryPassword);setForm({fullName:'',email:'',whatsapp:'',country:''});router.refresh()}catch(e){setMsg(e instanceof Error?e.message:'Unable to add partner.')}finally{setBusy(false)}}
 async function update(id:string,payload:any){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/influencer-partners',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,...payload})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to update partner.');setRows(x=>x.map(p=>p.id===id?{...p,...d.partner}:p))}catch(e){setMsg(e instanceof Error?e.message:'Unable to update partner.')}finally{setBusy(false)}}
 async function payout(id:string,statusValue:string){if(role!=='SUPER_ADMIN')return;const reason=statusValue==='REJECTED'?window.prompt('Reason for rejection?')||'Payment request rejected.':undefined;setBusy(true);try{const r=await fetch('/api/admin/influencer-payouts',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status:statusValue,reason})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to process payout.');router.refresh()}catch(e){setMsg(e instanceof Error?e.message:'Unable to process payout.')}finally{setBusy(false)}}
 return <div className="grid gap-7">
  <div className="card p-5"><div className="flex flex-wrap gap-3"><input placeholder="Search by name" value={q} onChange={e=>setQ(e.target.value)} className="max-w-sm"/><select value={country} onChange={e=>setCountry(e.target.value)} className="max-w-xs"><option value="">All countries</option>{countries.map(c=><option key={c}>{c}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="max-w-xs"><option value="">All statuses</option><option value="PENDING">Pending</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select></div></div>
  {role==='SUPER_ADMIN'&&<div className="card p-6"><div className="eyebrow">Add Partner</div><div className="mt-4 grid gap-4 md:grid-cols-4"><input placeholder="Full name" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/><input placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="WhatsApp" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/><input placeholder="Country" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></div><button disabled={busy} onClick={add} className="btn btn-primary mt-4">Add Partner</button></div>}
  {msg&&<div className="border border-gold/30 bg-white p-4 text-sm text-forest">{msg}</div>}
  <div className="card overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr>{['Name','Country','Status','Sales','Bookings','Commission Due','Commission Paid','Actions'].map(h=><th key={h} className="px-4 py-4 text-left">{h}</th>)}</tr></thead><tbody>{filtered.length===0?<tr><td colSpan={8} className="p-12 text-center text-forest/45">No partners found.</td></tr>:filtered.map(p=><tr key={p.id} className="border-t border-forest/10"><td className="px-4 py-4"><div className="font-semibold text-forest">{p.full_name}</div><div className="text-xs text-forest/40">{p.slug}</div></td><td className="px-4 py-4">{p.country}</td><td className="px-4 py-4"><select value={p.status} disabled={busy} onChange={e=>update(p.id,{status:e.target.value,suspensionReason:e.target.value==='SUSPENDED'?'Administrative decision':undefined})}><option value="PENDING">Pending</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select></td><td className="px-4 py-4">$ {Number(p.sales).toLocaleString()}</td><td className="px-4 py-4">{p.bookings}</td><td className="px-4 py-4">$ {Number(Math.max(0,p.due)).toLocaleString()}</td><td className="px-4 py-4">$ {Number(p.paid).toLocaleString()}</td><td className="px-4 py-4"><a className="font-semibold text-gold" href={'/admin/influencer-partners/'+p.id}>Open</a></td></tr>)}</tbody></table></div>
  <div className="card overflow-x-auto"><div className="border-b border-forest/10 p-6"><div className="eyebrow">Payout Requests</div></div><table className="w-full min-w-[850px] text-sm"><thead><tr>{['Partner','Amount','Date','Status','Action'].map(h=><th key={h} className="px-4 py-4 text-left">{h}</th>)}</tr></thead><tbody>{payouts.filter(p=>p.status==='REQUESTED').map(p=><tr key={p.id} className="border-t border-forest/10"><td className="px-4 py-4">{rows.find(x=>x.id===p.partner_id)?.full_name||'—'}</td><td className="px-4 py-4">$ {Number(p.amount).toLocaleString()}</td><td className="px-4 py-4">{new Date(p.requested_at).toLocaleDateString('en-GB')}</td><td className="px-4 py-4">{p.status}</td><td className="px-4 py-4">{role==='SUPER_ADMIN'&&<div className="flex gap-2"><button disabled={busy} className="btn btn-primary" onClick={()=>payout(p.id,'PAID')}>Mark Paid</button><button disabled={busy} className="btn btn-outline" onClick={()=>payout(p.id,'REJECTED')}>Reject</button></div>}</td></tr>)}</tbody></table></div>
 </div>;
}