"use client";
import {useMemo,useState} from "react";
type Cost={id:string;category:string;description:string;quantity:number;amount:number;currency:string;amount_usd:number|null;cost_stage:string;date:string;supplier_id?:string|null;notes?:string|null};
const cats=[["HOTEL","الفنادق"],["TRANSPORTATION","النقل"],["TRAIN","قطار الحرمين"],["EXPERIENCE","الفعاليات والتجارب"],["HOST","المضيف"],["OTHER","أخرى"]];
const money=(n:number,c="USD")=>`${c} ${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
export default function JourneyFinancials({bookingId,revenue,guestCount,costs,canEdit}:{bookingId:string;revenue:number;guestCount:number;costs:Cost[];canEdit:boolean}){
 const [rows,setRows]=useState(costs);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 const actual=useMemo(()=>rows.filter(x=>x.cost_stage==="ACTUAL"),[rows]);
 const planned=useMemo(()=>rows.filter(x=>x.cost_stage==="PLANNED"),[rows]);
 const sum=(a:Cost[])=>a.reduce((n,x)=>n+Number(x.amount_usd||0),0);
 const actualUsd=sum(actual),plannedUsd=sum(planned),profit=revenue-actualUsd,margin=revenue>0?(profit/revenue)*100:0;
 const byCat=(cat:string,stage:string)=>rows.filter(x=>x.category===cat&&x.cost_stage===stage).reduce((n,x)=>n+Number(x.amount_usd||0),0);
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const amount=Number(f.get("amount"));const currency=String(f.get("currency"));const fx=currency==="USD"?1:currency==="SAR"?0.2666666667:Number(f.get("fx_rate")||0);const body={action:"journey_cost",booking_id:bookingId,category:f.get("category"),description:f.get("description"),quantity:f.get("quantity"),amount,currency,cost_stage:f.get("cost_stage"),date:f.get("date"),fx_rate_to_usd:fx,supplier_id:f.get("supplier_id")||null,notes:f.get("notes")};const r=await fetch("/api/admin/finance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(r.ok){setRows(x=>[j.data,...x]);setMsg("تم تسجيل التكلفة.");e.currentTarget.reset()}else setMsg(j.error||"تعذر تسجيل التكلفة.");setBusy(false)}
 return <section className="card overflow-hidden">
  <div className="border-b border-forest/10 bg-[#f7f3ea] p-6">
   <div className="eyebrow">الملف المالي للرحلة</div><div className="mt-2 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
    <div><h2 className="serif text-3xl text-forest">تكلفة هذه الرحلة بالتحديد</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-forest/55">سجّل تكلفة الفندق والنقل والقطار والفعاليات والمضيف وأي مصروف آخر على الحجز نفسه، بدل خلطها مع مصروفات الشركة العامة.</p></div>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-xl bg-white p-3"><div className="text-[11px] text-forest/45">الإيراد</div><b>{money(revenue)}</b></div><div className="rounded-xl bg-white p-3"><div className="text-[11px] text-forest/45">التكلفة الفعلية</div><b>{money(actualUsd)}</b></div><div className="rounded-xl bg-white p-3"><div className="text-[11px] text-forest/45">المتبقي</div><b>{money(Math.max(profit,0))}</b></div><div className="rounded-xl bg-white p-3"><div className="text-[11px] text-forest/45">الهامش</div><b>{margin.toFixed(1)}%</b></div></div>
   </div>
  </div>
  {canEdit&&<form onSubmit={add} className="grid gap-3 p-6 sm:grid-cols-2 lg:grid-cols-4">
   <select name="category" defaultValue="HOTEL">{cats.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input name="description" required placeholder="مثال: فندق مكة — 9 ليالٍ"/><input name="quantity" type="number" min="0.01" step="0.01" defaultValue="1" placeholder="الكمية"/><input name="amount" required type="number" min="0" step="0.01" placeholder="إجمالي التكلفة"/>
   <select name="currency"><option>USD</option><option>SAR</option><option>OTHER</option></select><input name="fx_rate" type="number" min="0.000001" step="0.000001" placeholder="سعر الصرف إلى USD عند الحاجة"/><select name="cost_stage"><option value="ACTUAL">تكلفة فعلية</option><option value="PLANNED">تكلفة متوقعة</option></select><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><input name="notes" placeholder="ملاحظات" className="sm:col-span-2"/><button className="btn btn-primary" disabled={busy}>{busy?"جارٍ الحفظ…":"إضافة تكلفة للرحلة"}</button>
  </form>}
  {msg&&<div className="px-6 pb-4 text-sm text-forest/60">{msg}</div>}
  <div className="grid gap-3 border-t border-forest/10 p-6 sm:grid-cols-2 lg:grid-cols-3">{cats.map(([cat,label])=><div key={cat} className="rounded-2xl border border-forest/10 bg-white p-4"><div className="text-xs text-forest/45">{label}</div><div className="mt-1 text-xl font-semibold text-forest">{money(byCat(cat,"ACTUAL"))}</div><div className="mt-1 text-xs text-forest/40">متوقع: {money(byCat(cat,"PLANNED"))}</div></div>)}</div>
  <div className="overflow-x-auto border-t border-forest/10"><table className="w-full min-w-[900px] text-sm"><thead><tr>{["التاريخ","البند","التصنيف","المرحلة","الكمية","التكلفة","بالدولار","ملاحظات"].map(h=><th key={h} className="px-4 py-3 text-left text-xs text-forest/45">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id} className="border-t border-forest/8"><td className="px-4 py-3">{x.date}</td><td className="px-4 py-3 font-semibold">{x.description}</td><td className="px-4 py-3">{cats.find(c=>c[0]===x.category)?.[1]||x.category}</td><td className="px-4 py-3">{x.cost_stage==="ACTUAL"?"فعلي":"متوقع"}</td><td className="px-4 py-3">{x.quantity}</td><td className="px-4 py-3">{money(x.amount,x.currency)}</td><td className="px-4 py-3">{x.amount_usd!=null?money(x.amount_usd):"يحتاج سعر صرف"}</td><td className="px-4 py-3">{x.notes||"—"}</td></tr>):<tr><td colSpan={8} className="p-10 text-center text-forest/40">لم تسجل تكاليف لهذه الرحلة بعد.</td></tr>}</tbody></table></div>
  <div className="flex flex-col gap-2 border-t border-forest/10 bg-[#fbfaf6] p-5 text-xs text-forest/55 sm:flex-row sm:justify-between"><span>التكلفة الفعلية: {money(actualUsd)} · المتوقعة: {money(plannedUsd)}</span><span>الحساب الربحي يعتمد فقط على التكاليف التي لها قيمة محولة إلى USD.</span></div>
 </section>
}