'use client';

import { useState } from 'react';
import { FileDown, MessageCircle, ShieldCheck } from 'lucide-react';

type Service = { id: string; title: string; city?: string | null; date?: string | null; status?: string | null; reference?: string | null; details?: string | null };
type Props = { booking: { id: string; bookingId: string; guestName: string; whatsapp: string; guests: number; packageName: string; paymentStatus: string; bookingStatus: string; travelDate?: string | null; groupId?: string | null }; hotels: Service[]; trains: Service[]; activities: Service[]; locale: 'ar' | 'en' };

const labels = {
 ar: { eyebrow:'ALHARAMAIN ELITE · مراجعة الإدارة', title:'مراجعة تأكيد الرحلة', description:'اختر لغة ملف العميل، راجع البيانات والخدمات، ثم نزّل PDF وأرسله بنفسك عبر واتساب.', language:'لغة ملف العميل', ar:'العربية', en:'English', booking:'رقم الحجز', guest:'صاحب الحجز', guests:'عدد الضيوف', package:'الباقة', date:'موعد السفر المتوقع', payment:'حالة الدفع', received:'تم التحقق من الدفع', pending:'الدفع غير معتمد', bookingPending:'يجب تأكيد الحجز أولًا.', servicesPending:'يلزم تسجيل فندق واحد على الأقل وجولة/زيارة واحدة قبل إصدار التأكيد.', hotels:'الفنادق والغرف', trains:'قطارات الحرمين', activities:'الزيارات والجولات', empty:'لا توجد بيانات مسجلة لهذا القسم.', checklist:'قائمة المراجعة قبل الإصدار', c1:'بيانات العميل وعدد الضيوف صحيحة', c2:'التواريخ والمدن صحيحة', c3:'راجعت تأكيدات الخدمات الفعلية وأرقامها', c4:'راجعت المجموعة وتوزيع الغرف إن وُجدا', missing:'أكمل جميع عناصر المراجعة وتحقق من الدفع قبل إصدار التأكيد النهائي.', pdf:'تنزيل / طباعة PDF', wa:'فتح واتساب العميل', waHint:'يفتح واتساب برسالة جاهزة فقط. أرفق ملف PDF الذي نزّلته ثم أرسله يدويًا.', noPhone:'لا يوجد رقم واتساب مسجل لهذا العميل.', preview:'معاينة داخلية — ليست تأكيدًا نهائيًا حتى تكتمل المراجعة.', status:'الحالة المسجلة', ref:'رقم التأكيد / التذكرة', notProvided:'غير مسجل', generated:'تاريخ إصدار النسخة', contact:'للتواصل مع فريق ALHARAMAIN ELITE', note:'تعكس هذه النسخة البيانات المسجلة وقت إصدارها. يرجى التواصل معنا إذا لاحظتم أي اختلاف.', message:'مرحبًا {name}، نرفق لكم ملف تأكيد رحلة العمرة من ALHARAMAIN ELITE. يرجى مراجعة التفاصيل والاحتفاظ بالملف أثناء الرحلة. لأي استفسار، تواصلوا معنا مباشرة.' },
 en: { eyebrow:'ALHARAMAIN ELITE · ADMIN REVIEW', title:'Journey confirmation review', description:'Choose the customer document language, review the details and services, then download the PDF and send it yourself on WhatsApp.', language:'Customer document language', ar:'العربية', en:'English', booking:'Booking reference', guest:'Lead guest', guests:'Guests', package:'Package', date:'Expected travel date', payment:'Payment status', received:'Payment verified', pending:'Payment not approved', bookingPending:'The booking must be confirmed first.', servicesPending:'At least one hotel and one visit/tour must be recorded before issuing confirmation.', hotels:'Hotels & rooms', trains:'Haramain trains', activities:'Visits & tours', empty:'No records are currently attached to this section.', checklist:'Pre-issue review checklist', c1:'Customer details and guest count are correct', c2:'Travel dates and cities are correct', c3:'Actual service confirmations and references checked', c4:'Group and room assignments reviewed, if applicable', missing:'Complete every review item and verify payment before issuing the final confirmation.', pdf:'Download / Print PDF', wa:'Open customer WhatsApp', waHint:'WhatsApp opens with a prepared message only. Attach the downloaded PDF and send it manually.', noPhone:'No WhatsApp number is recorded for this customer.', preview:'Internal preview — not a final confirmation until review is complete.', status:'Recorded status', ref:'Confirmation / ticket reference', notProvided:'Not recorded', generated:'Document issue date', contact:'Contact the ALHARAMAIN ELITE team', note:'This document reflects information recorded at the time of issue. Contact us if anything appears incorrect.', message:'Hello {name}, attached is your Umrah journey confirmation from ALHARAMAIN ELITE. Please review the details and keep the document with you during your journey. Contact us directly if you need assistance.' }
};

function dateLabel(value: string | null | undefined, language: 'ar' | 'en') {
 if (!value) return '—';
 const d = new Date(value);
 return Number.isNaN(d.getTime()) ? value : d.toLocaleDateString(language === 'ar' ? 'ar-SA' : 'en-GB', { year:'numeric', month:'short', day:'numeric' });
}
function esc(value: unknown) { return String(value ?? '—').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] || c)); }

export function JourneyConfirmationReview({ booking, hotels, trains, activities, locale }: Props) {
 const [language, setLanguage] = useState<'ar'|'en'>(locale);
 const [checks, setChecks] = useState([false,false,false,false]);
 const [error, setError] = useState('');
 const t = labels[locale]; const d = labels[language];
 const paid = booking.paymentStatus === 'RECEIVED';
 const ready = paid && checks.every(Boolean);
 const services = [{title:d.hotels,items:hotels},{title:d.trains,items:trains},{title:d.activities,items:activities}];

 function printPdf() {
  if (!ready) { setError(t.missing); return; }
  const sections = services.map((section) => {
   const items = section.items.length ? section.items.map((item) =>
    '<article class="service"><h3>' + esc(item.title) + '</h3><p>' + esc([item.city,item.details].filter(Boolean).join(' · ') || '—') + '</p><p>' + esc(d.date) + ': ' + esc(dateLabel(item.date,language)) + '</p><p>' + esc(d.status) + ': ' + esc(item.status || d.notProvided) + '</p><p>' + esc(d.ref) + ': ' + esc(item.reference || d.notProvided) + '</p></article>'
   ).join('') : '<p class="empty">' + esc(d.empty) + '</p>';
   return '<section><h2>' + esc(section.title) + '</h2>' + items + '</section>';
  }).join('');
  const html = '<!doctype html><html lang="' + language + '" dir="' + (language === 'ar' ? 'rtl':'ltr') + '"><head><meta charset="utf-8"><title>' + esc(d.title) + ' - ' + esc(booking.bookingId) + '</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{font-family:Arial,"Noto Sans Arabic",sans-serif;color:#173f35;margin:0;line-height:1.65;font-size:12px}.top{background:#063f35;color:#fff;padding:26px 30px;border-bottom:5px solid #c9a227}.brand{font-size:14px;letter-spacing:2px;color:#e6d7a4;font-weight:bold}.tag{font-size:10px;color:#f7f3ea}.heading{font-size:26px;margin:22px 0 6px}.ref{font-size:13px;color:#e6d7a4}.summary{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:20px 0}.cell,.service{padding:12px;border:1px solid #e5e9e4;border-radius:10px;background:#fbfaf6;break-inside:avoid}.label{font-size:10px;color:#697b73}.value{font-size:13px;font-weight:bold}h2{font-size:16px;border-bottom:1px solid #c9a227;padding-bottom:7px;margin:24px 0 10px}.service{margin:8px 0}.service h3{font-size:13px;margin:0 0 5px}.service p{margin:4px 0}.empty{padding:12px;background:#fbfaf6;color:#687a73}.foot{border-top:1px solid #e4e7e1;margin-top:25px;padding-top:12px;color:#64746c;font-size:10px}</style></head><body><header class="top"><div class="brand"><img src="' + esc(window.location.origin) + '/brand/alharamainelite-logo.png" alt="ALHARAMAIN ELITE" style="width:190px;max-height:64px;object-fit:contain;object-position:left center;display:block" /><span>ALHARAMAIN ELITE</span></div><div class="tag">A JOURNEY WORTH REMEMBERING.</div><h1 class="heading">' + esc(d.title) + '</h1><div class="ref">' + esc(d.booking) + ': ' + esc(booking.bookingId) + '</div></header><main><div class="summary"><div class="cell"><div class="label">' + esc(d.guest) + '</div><div class="value">' + esc(booking.guestName) + '</div></div><div class="cell"><div class="label">' + esc(d.package) + '</div><div class="value">' + esc(booking.packageName) + '</div></div><div class="cell"><div class="label">' + esc(d.guests) + '</div><div class="value">' + esc(booking.guests) + '</div></div><div class="cell"><div class="label">' + esc(d.date) + '</div><div class="value">' + esc(dateLabel(booking.travelDate,language)) + '</div></div></div><p><b>' + esc(d.payment) + ':</b> ' + esc(d.received) + '</p>' + sections + '<footer class="foot"><b>ALHARAMAIN ELITE</b><p>' + esc(d.contact) + '</p><p>' + esc(d.note) + '</p><p>' + esc(d.generated) + ': ' + esc(dateLabel(new Date().toISOString(),language)) + '</p><p>' + esc('A JOURNEY WORTH REMEMBERING.') + '</p></footer></main><script>window.onload=function(){window.print()}</script></body></html>';
  const popup = window.open('', '_blank');
  if (!popup) { setError(locale === 'ar' ? 'يرجى السماح بالنوافذ المنبثقة لإنشاء PDF.' : 'Allow pop-ups to create the PDF.'); return; }
  popup.document.open(); popup.document.write(html); popup.document.close();
 }
 function openWhatsApp() {
  const phone = booking.whatsapp.replace(/[^\d]/g,'');
  if (!phone) { setError(t.noPhone); return; }
  const message = d.message.replace('{name}',booking.guestName || (language === 'ar' ? 'ضيفنا الكريم':'Guest'));
  window.open('https://wa.me/' + phone + '?text=' + encodeURIComponent(message),'_blank','noopener,noreferrer');
 }
 return <section className="pb-12">
  <div className="rounded-2xl bg-[#063f35] p-6 text-white sm:p-8"><div className="text-xs font-semibold tracking-[0.18em] text-[#c9a227]">{t.eyebrow}</div><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><h1 className="serif text-3xl sm:text-4xl">{t.title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/75">{t.description}</p></div><div className="rounded-xl border border-white/15 bg-white/5 px-4 py-3"><div className="text-xs text-white/60">{t.booking}</div><div className="mt-1 font-semibold">{booking.bookingId}</div></div></div></div>
  <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-5">
   <div className="card p-5 sm:p-6"><h2 className="text-lg font-semibold text-forest">{t.title}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[[t.guest,booking.guestName],[t.package,booking.packageName],[t.guests,String(booking.guests)],[t.date,dateLabel(booking.travelDate,locale)],[t.booking,booking.bookingId],[t.payment,paid?t.received:t.pending]].map(([label,value])=><div key={label} className="rounded-xl bg-[#f7f3ea] p-3"><div className="text-xs text-forest/55">{label}</div><div className="mt-1 break-words text-sm font-semibold text-forest">{value}</div></div>)}</div></div>
   {services.map((section)=><div className="card p-5 sm:p-6" key={section.title}><h2 className="text-lg font-semibold text-forest">{section.title}</h2>{section.items.length ? <div className="mt-3 space-y-3">{section.items.map((item)=><div key={item.id} className="rounded-xl border border-forest/10 p-4"><div className="font-semibold text-forest">{item.title}</div><p className="mt-2 text-sm text-forest/65">{[item.city,item.details].filter(Boolean).join(' · ') || '—'}</p><div className="mt-2 grid gap-1 text-xs text-forest/55 sm:grid-cols-2"><span>{t.date}: {dateLabel(item.date,locale)}</span><span>{t.ref}: {item.reference || t.notProvided}</span><span>{t.status}: {item.status || t.notProvided}</span></div></div>)}</div>:<p className="mt-3 rounded-xl bg-[#f7f3ea] p-4 text-sm text-forest/60">{t.empty}</p>}</div>)}
  </div><aside className="h-fit space-y-4 lg:sticky lg:top-5"><div className="card p-5"><div className="flex items-center gap-2 text-forest"><ShieldCheck size={20}/><h2 className="font-semibold">{t.checklist}</h2></div><div className="mt-4 space-y-3">{[t.c1,t.c2,t.c3,t.c4].map((label,index)=><label key={label} className="flex cursor-pointer items-start gap-3 text-sm leading-5 text-forest/80"><input type="checkbox" className="mt-1 accent-[#063f35]" checked={checks[index]} onChange={(event)=>setChecks((current)=>current.map((value,i)=>i===index?event.target.checked:value))}/><span>{label}</span></label>)}</div><div className={'mt-4 rounded-xl p-3 text-xs leading-5 '+(ready?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-900')}>{!paid?t.missing:!bookingConfirmed?t.bookingPending:!requiredServicesReady?t.servicesPending:ready?(locale==='ar'?'اكتملت قائمة المراجعة. يمكنك إنشاء نسخة للمراجعة النهائية.':'Review checklist complete. You may create the final-review copy.'):t.missing}</div><label className="mt-5 block text-sm font-semibold text-forest">{t.language}</label><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setLanguage('ar')} aria-pressed={language==='ar'} className={'rounded-xl border px-3 py-2 text-sm '+(language==='ar'?'border-[#063f35] bg-[#063f35] text-white':'border-forest/15 text-forest')}>{t.ar}</button><button type="button" onClick={()=>setLanguage('en')} aria-pressed={language==='en'} className={'rounded-xl border px-3 py-2 text-sm '+(language==='en'?'border-[#063f35] bg-[#063f35] text-white':'border-forest/15 text-forest')}>{t.en}</button></div><button type="button" onClick={()=>{setError('');printPdf()}} disabled={!ready} className="btn btn-primary mt-4 flex w-full items-center justify-center gap-2 disabled:cursor-not-allowed disabled:opacity-45"><FileDown size={17}/>{t.pdf}</button><button type="button" onClick={()=>{setError('');openWhatsApp()}} disabled={!ready} className="btn btn-outline mt-2 flex w-full items-center justify-center gap-2 disabled:cursor-not-allowed disabled:opacity-45"><MessageCircle size={17}/>{t.wa}</button><p className="mt-3 text-xs leading-5 text-forest/55">{t.waHint}</p>{error&&<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-800">{error}</p>}</div><div className="rounded-2xl border border-[#c9a227]/40 bg-[#fffaf0] p-4 text-xs leading-5 text-forest/70">{t.preview}</div></aside></div>
 </section>;
}
