"use client";
import {useMemo,useState} from "react";
type Cost={id:string;category:string;description:string;quantity:number;amount:number;currency:"USD"|"SAR";amount_usd:number|null;cost_stage:string;date:string;notes?:string|null};
const cats=[["HOTEL","الفنادق"],["TRANSPORTATION","النقل"],["TRAIN","قطار الحرمين"],["EXPERIENCE","الفعاليات والتجارب"],["HOST","المضيف"],["OTHER","أخرى"]];
const money=(n:number,c="USD")=>`${c} ${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
export default function JourneyFinancials({bookingId,revenue,guestCount,costs,canEdit}:{bookingId:string;revenue:number;guestCount:number;costs:Cost[];canEdit:boolean}){
 const [rows,setRows]=useState(costs);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 const totalUsd=useMemo(()=>rows.reduce((n,x)=>n+Number(x.amount_usd||0),0),[rows]);
 const profit=revenue-totalUsd,margin=revenue>0?(profit/revenue)*100:0;
 const byCat=(cat:string)=>rows.filter(x=>x.category===cat).reduce((n,x)=>n+Number(x.amount_usd||0),0);
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const amount=Number(f.get("amount"));const body={action:"journey_cost",booking_id:bookingId,category:f.get("category"),description:f.get("description"),quantity:1,amount,currency:f.get("currency"),date:f.get("date"),notes:f.get("notes")};const r=await fetch("/api/admin/finance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(r.ok){setRows(x=>[j.data,...x]);setMsg("تم تسجيل المصروف على هذه الرحلة.");e.currentTarget.reset()}else setMsg(j.error||"تعذر تسجيل المصروف.");setBusy(false)}
 return <section className="card overflow-hidden">
  <div className="border-b border-forest/10 bg-[#f7f3ea] p-6"><div className="eyebrow">الملف المالي للرحلة</div><div className="mt-2 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="serif text-3xl text-forest">مصروفات هذه الرحلة بالتحديد</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-forest/55">سجّل أي مصروف يخص هذه الرحلة فقط: الفندق، النقل، القطار، الفعاليات، المضيف أو أي مصروف آخر. المصروفات العامة للشركة تبقى منفصلة.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-xl bg-white p-3"><div className="text-[11px] text-forest/45">الإيراد</div><b>{money(revenue)}</b></div><div className="rounded-xl bg-white p-3"><div className="text-[11px] text-forest/45">إجمالي المصروفات</div><b>{money(totalUsd)}</b></div><div className="rounded-xl bg-white p-3"><div className="text-[11px] text-forest/45">المتبقي</div><b>{money(Math.max(profit,0))}</b></div><div className="rounded-xl bg-white p-3"><div className="text-[11px] text-forest/45">الهامش</div><b>{margin.toFixed(1)}%</b></div></div></div></div>
  {canEdit&&<form onSubmit={add} className="grid gap-3 p-6 sm:grid-cols-2 lg:grid-cols-5">
   <select name="category" defaultValue="HOTEL">{cats.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input name="description" required placeholder="مثال: فندق مكة — 9 ليالٍ"/><input name="amount" required type="number" min="0" step="0.01" placeholder="المبلغ"/><select name="currency" defaultValue="SAR"><option value="SAR">ريال سعودي (SAR)</option><option value="USD">دولار أمريكي (USD)</option></select><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><input name="notes" placeholder="ملاحظات" className="sm:col-span-2 lg:col-span-3"/><button className="btn btn-primary" disabled={busy}>{busy?"جارٍ الحفظ…":"إضافة مصروف للرحلة"}</button>
  </form>}
  {msg&&<div className="px-6 pb-4 text-sm text-forest/60">{msg}</div>}
  <div className="grid gap-3 border-t border-forest/10 p-6 sm:grid-cols-2 lg:grid-cols-3">{cats.map(([cat,label])=><div key={cat} className="rounded-2xl border border-forest/10 bg-white p-4"><div className="text-xs text-forest/45">{label}</div><div className="mt-1 text-xl font-semibold text-forest">{money(byCat(cat))}</div><div className="mt-1 text-xs text-forest/40">بالدولار بعد التحويل التلقائي</div></div>)}</div>
  <div className="overflow-x-auto border-t border-forest/10"><table className="w-full min-w-[760px] text-sm"><thead><tr>{["التاريخ","البند","التصنيف","المبلغ","العملة","بالدولار","ملاحظات"].map(h=><th key={h} className="px-4 py-3 text-right text-xs text-forest/45">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id} className="border-t border-forest/8"><td className="px-4 py-3">{x.date}</td><td className="px-4 py-3 font-semibold">{x.description}</td><td className="px-4 py-3">{cats.find(c=>c[0]===x.category)?.[1]||x.category}</td><td className="px-4 py-3">{Number(x.amount).toLocaleString(undefined,{maximumFractionDigits:2})}</td><td className="px-4 py-3 font-semibold">{x.currency}</td><td className="px-4 py-3">{x.amount_usd!=null?money(x.amount_usd):"—"}</td><td className="px-4 py-3">{x.notes||"—"}</td></tr>):<tr><td colSpan={7} className="p-10 text-center text-forest/40">لم تسجل مصروفات لهذه الرحلة بعد.</td></tr>}</tbody></table></div>
  <div className="border-t border-forest/10 bg-[#fbfaf6] p-5 text-xs text-forest/55">الأسعار بالريال والدولار فقط. التحويل إلى الدولار يتم تلقائيًا داخل النظام للحساب المالي، ولا يحتاج الموظف إلى إدخال سعر صرف.</div>
 </section>
}