import type {Metadata} from 'next';
import Link from 'next/link';
import Script from 'next/script';
import {notFound} from 'next/navigation';
import {headers} from 'next/headers';
import {isLocale,defaultLocale,type Locale} from '@/lib/i18n';
import {SITE_URL,localizedPath,hreflangAlternates} from '@/lib/seo';
import {CITY_SEO,getCitySeo} from '@/lib/city-seo';

export const dynamicParams=false;
export function generateStaticParams(){return CITY_SEO.map(city=>({city:city.slug}));}

const labels={en:{eyebrow:'SOMALI UMRAH · CITY GUIDE',intro:'A premium small-group Umrah planning experience for Somali Muslims in',price:'Transparent package pricing',priceText:'SIGNATURE is $2,000 per guest. ELITE is $2,500 per guest. Both are 10 days / 9 nights.',group:'Small groups',groupText:'Plan for 5–8 guests and share an expected travel date or period.',support:'Language & support',supportText:'English, Somali and Arabic support is available throughout the planning journey.',local:'Local planning area',airport:'Departure airport',start:'Start your journey',request:'Request your journey',packages:'View packages',faq:'Common planning questions',flight:'Do I need confirmed flights?',flightText:'No. An expected travel date or approximate period is enough to begin a journey request.',guests:'How many guests can travel together?',guestsText:'The launch packages are designed for groups of 5–8 guests.',cities:'Explore other Somali diaspora cities',country:'Explore the wider country page'},
so:{eyebrow:'CUMRO SOOMAALI AH · HAGIDA MAGAALADA',intro:'Qorshayn safar Cumro oo heer sare ah oo koox yar ah oo loogu talagalay Muslimiinta Soomaalida ku nool',price:'Qiime xirmo oo cad',priceText:'SIGNATURE waa $2,000 qofkiiba. ELITE waa $2,500 qofkiiba. Labaduba waa 10 maalmood / 9 habeen.',group:'Kooxo yaryar',groupText:'Qorshee 5–8 marti oo nala wadaag taariikhda ama muddada aad filayso.',support:'Luqad iyo taageero',supportText:'Taageerada English, Soomaali iyo Carabi waxay qayb ka tahay qorshaynta safarka.',local:'Aagga qorshaynta',airport:'Garoonka bixitaanka',start:'Bilow safarkaaga',request:'Codso safarkaaga',packages:'Eeg xirmooyinka',faq:'Su’aalaha qorshaynta',flight:'Ma u baahanahay duulimaad la xaqiijiyey?',flightText:'Maya. Taariikh la filayo ama muddo qiyaas ah ayaa ku filan bilowga codsiga.',guests:'Immisa marti ayaa wada safri kara?',guestsText:'Xirmooyinka bilowga ah waxaa loogu talagalay kooxo 5–8 marti ah.',cities:'Sahami magaalooyinka kale ee Soomaalida',country:'Sahami bogga dalka'},
ar:{eyebrow:'عمرة للصوماليين · دليل المدينة',intro:'تخطيط رحلة عمرة راقية ضمن مجموعة صغيرة للمسلمين الصوماليين المقيمين في',price:'أسعار واضحة للباقات',priceText:'SIGNATURE بسعر 2,000 دولار للضيف وELITE بسعر 2,500 دولار للضيف. مدة كل رحلة 10 أيام و9 ليالٍ.',group:'مجموعات صغيرة',groupText:'خطط لمجموعة من 5–8 ضيوف وشاركنا تاريخ السفر أو الفترة المتوقعة.',support:'اللغة والدعم',supportText:'الدعم بالإنجليزية والصومالية والعربية متاح خلال مرحلة التخطيط.',local:'منطقة التخطيط',airport:'مطار المغادرة',start:'ابدأ رحلتك',request:'اطلب رحلتك',packages:'استكشف الباقات',faq:'أسئلة شائعة عن التخطيط',flight:'هل أحتاج إلى رحلات مؤكدة؟',flightText:'لا. يكفي تاريخ متوقع أو فترة تقريبية لبدء طلب الرحلة.',guests:'كم عدد الضيوف في المجموعة؟',guestsText:'الباقات عند الإطلاق مصممة لمجموعات من 5 إلى 8 ضيوف.',cities:'استكشف مدن الجالية الصومالية الأخرى',country:'استكشف صفحة الدولة'}} as const;

function title(city:string,locale:Locale){return locale==='ar'?'العمرة من '+city+' للمسلمين الصوماليين | AlHaramain Elite':locale==='so'?'Cumro ka socota '+city+' ee Muslimiinta Soomaalida | AlHaramain Elite':'Umrah from '+city+' for Somali Muslims | AlHaramain Elite';}
function description(city:string,locale:Locale){return locale==='ar'?'خطط لرحلة عمرة راقية ضمن مجموعة صغيرة من '+city+' للمسلمين الصوماليين، بأسعار واضحة ودعم شخصي.':locale==='so'?'Qorshee safar Cumro oo koox yar ah oo ka socda '+city+' Muslimiinta Soomaalida, leh qiime cad iyo taageero gaar ah.':'Plan a premium small-group Umrah journey from '+city+' for Somali Muslims with transparent pricing and personal support.';}

export async function generateMetadata({params}:{params:Promise<{city:string}>}):Promise<Metadata>{const p=await params;const city=getCitySeo(p.city);if(!city)return{};const h=await headers();const raw=h.get('x-he-locale');const locale:Locale=isLocale(raw??undefined)?(raw as Locale):defaultLocale;const path='/umrah-from-city/'+city.slug;const t=title(city.city,locale);const d=description(city.city,locale);return{title:t,description:d,alternates:{canonical:SITE_URL+localizedPath(path,locale),languages:hreflangAlternates(path)},openGraph:{title:t,description:d,type:'website',url:SITE_URL+localizedPath(path,locale),images:[{url:SITE_URL+'/brand/alharamainelite-logo.png'}]},robots:{index:true,follow:true}};}

export default async function CityPage({params}:{params:Promise<{city:string}>}){const p=await params;const city=getCitySeo(p.city);if(!city)notFound();const h=await headers();const raw=h.get('x-he-locale');const locale:Locale=isLocale(raw??undefined)?(raw as Locale):defaultLocale;const t=labels[locale];const path='/umrah-from-city/'+city.slug;const url=SITE_URL+localizedPath(path,locale);const nonce=h.get('x-nonce')||undefined;const same=CITY_SEO.filter(x=>x.country===city.country&&x.slug!==city.slug).slice(0,6);const countrySlug=city.country==='United States'?'usa':city.country==='United Kingdom'?'uk':city.country==='Canada'?'canada':null;const schema={'@context':'https://schema.org','@type':'WebPage','name':title(city.city,locale),'description':description(city.city,locale),'url':url,'inLanguage':locale,'about':{'@type':'Service','name':'Umrah Journey Planning','areaServed':{'@type':'City','name':city.city}},'isPartOf':{'@type':'WebSite','name':'ALHARAMAIN ELITE','url':SITE_URL}};return <div>
<section className="relative overflow-hidden bg-forest text-white"><div className="container py-24 md:py-32"><div className="max-w-4xl"><div className="eyebrow">{t.eyebrow} · {city.countryCode}</div><h1 className="serif mt-5 text-5xl leading-[.98] md:text-7xl">{locale==='ar'?'العمرة من '+city.city+' للمسلمين الصوماليين':locale==='so'?'Cumro ka socota '+city.city+' ee Muslimiinta Soomaalida':city.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/75">{t.intro} {city.city}.</p><div className="mt-9 flex flex-wrap gap-3"><Link href={localizedPath('/request-journey',locale)} className="btn bg-gold text-forest">{t.request}</Link><Link href={localizedPath('/packages',locale)} className="btn border border-white/35 text-white">{t.packages}</Link></div></div></div></section>
<section className="section"><div className="container"><div className="grid gap-5 md:grid-cols-3"><div className="card p-7"><div className="eyebrow">{t.price}</div><h2 className="serif mt-3 text-3xl text-forest">$2,000 / $2,500</h2><p className="mt-3 text-sm leading-7 text-forest/60">{t.priceText}</p></div><div className="card p-7"><div className="eyebrow">{t.group}</div><h2 className="serif mt-3 text-3xl text-forest">5–8</h2><p className="mt-3 text-sm leading-7 text-forest/60">{t.groupText}</p></div><div className="card p-7"><div className="eyebrow">{t.support}</div><h2 className="serif mt-3 text-3xl text-forest">EN · SO · AR</h2><p className="mt-3 text-sm leading-7 text-forest/60">{t.supportText}</p></div></div></div></section>
<section className="section bg-[#f7f3ea]"><div className="container"><div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr]"><div><div className="eyebrow">{t.local}</div><h2 className="serif mt-3 text-4xl text-forest md:text-5xl">{city.localNote}</h2><p className="mt-5 max-w-3xl leading-8 text-forest/65">{city.travelNote}</p><div className="mt-7 flex flex-wrap gap-3">{city.areas.map(area=><span key={area} className="rounded-full border border-forest/15 bg-white px-4 py-2 text-sm text-forest/70">{area}</span>)}</div></div><aside className="card bg-white p-7"><div className="eyebrow">{t.airport}</div><h3 className="serif mt-3 text-3xl text-forest">{city.airport}</h3><p className="mt-3 text-sm leading-6 text-forest/60">{city.travelNote}</p></aside></div></div></section>
<section className="section"><div className="container"><div className="max-w-3xl"><div className="eyebrow">{t.faq}</div><h2 className="serif mt-3 text-4xl text-forest">{t.start} · {city.city}</h2></div><div className="mt-8 grid gap-5 md:grid-cols-2"><div className="card p-7"><h3 className="font-semibold text-forest">{t.flight}</h3><p className="mt-3 leading-7 text-forest/60">{t.flightText}</p></div><div className="card p-7"><h3 className="font-semibold text-forest">{t.guests}</h3><p className="mt-3 leading-7 text-forest/60">{t.guestsText}</p></div></div></div></section>
<section className="section bg-forest text-white"><div className="container"><div className="max-w-3xl"><div className="eyebrow">{t.start}</div><h2 className="serif mt-3 text-4xl">{locale==='ar'?'ابدأ رحلة العمرة من ':locale==='so'?'Bilow safarka Cumrada ee ':'Start your Umrah journey from '}{city.city}</h2><p className="mt-4 leading-7 text-white/70">{city.travelNote}</p><Link href={localizedPath('/request-journey',locale)} className="btn mt-7 bg-gold text-forest">{t.request}</Link></div></div></section>
<section className="section"><div className="container"><div className="max-w-3xl"><div className="eyebrow">{t.cities}</div><h2 className="serif mt-3 text-4xl text-forest">{t.cities}</h2></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{same.map(x=><Link key={x.slug} href={localizedPath('/umrah-from-city/'+x.slug,locale)} className="card p-5 hover:border-gold"><div className="eyebrow">{x.countryCode}</div><div className="mt-2 font-semibold text-forest">{x.city}</div></Link>)}</div></div></section>
<Script id="city-schema" nonce={nonce} type="application/ld+json">{JSON.stringify(schema)}</Script></div>;}
