drop index if exists public.expenses_booking_id_idx;
drop index if exists public.payments_booking_id_idx;
create index if not exists audit_logs_actor_id_idx on public.audit_logs(actor_id);
create index if not exists booking_activities_activity_id_idx on public.booking_activities(activity_id);
create index if not exists booking_activities_booking_id_idx on public.booking_activities(booking_id);
create index if not exists booking_activities_group_id_idx on public.booking_activities(group_id);
create index if not exists booking_guests_booking_id_idx on public.booking_guests(booking_id);
create index if not exists communication_logs_booking_id_idx on public.communication_logs(booking_id);
create index if not exists group_members_approved_by_idx on public.group_members(approved_by);
create index if not exists group_members_booking_id_idx on public.group_members(booking_id);
create index if not exists groups_hotel_jeddah_id_idx on public.groups(hotel_jeddah_id);
create index if not exists groups_hotel_madinah_id_idx on public.groups(hotel_madinah_id);
create index if not exists groups_hotel_makkah_id_idx on public.groups(hotel_makkah_id);
create index if not exists host_availability_host_id_idx on public.host_availability(host_id);
create index if not exists host_tasks_booking_id_idx on public.host_tasks(booking_id);
create index if not exists package_features_package_id_idx on public.package_features(package_id);
create index if not exists reviews_package_id_idx on public.reviews(package_id);
drop policy if exists profiles_admin_manage on public.profiles;
create policy profiles_admin_manage on public.profiles for all to authenticated using (has_role('ADMIN'::app_role)) with check (has_role('ADMIN'::app_role));
