alter table public.communication_templates
  drop constraint if exists communication_templates_key_key;
alter table public.communication_templates
  add constraint communication_templates_key_language_key unique (key, language);

-- Seeded by production migration; inserts are idempotent.
insert into public.communication_templates (key, language, subject, body, active)
select * from (values
('REQUEST_RECEIVED','en','Journey request received','Hello {{customer_name}},\n\nThank you for choosing ALHARAMAIN ELITE. We have received your journey request {{booking_id}} and our team will review the details with you shortly.\n\nA Journey Worth Remembering.',true),
('REQUEST_RECEIVED','so','Codsiga safarka waa la helay','Salaan {{customer_name}},\n\nWaad ku mahadsan tahay doorashada ALHARAMAIN ELITE. Waxaan helnay codsiga safarkaaga {{booking_id}}, kooxdayaduna waxay kula soo xiriiri doontaa faahfaahinta.\n\nA Journey Worth Remembering.',true),
('REQUEST_RECEIVED','ar','تم استلام طلب الرحلة','مرحبًا {{customer_name}}،\n\nشكرًا لاختيار ALHARAMAIN ELITE. تم استلام طلب رحلتكم رقم {{booking_id}}، وسيتواصل معكم فريقنا لمراجعة التفاصيل.\n\nA Journey Worth Remembering.',true),
('PAYMENT_INSTRUCTIONS','en','Payment instructions','Hello {{customer_name}},\n\nYour ALHARAMAIN ELITE journey request {{booking_id}} is ready for payment. The total journey value is {{currency}} {{total_amount}}.\n\nPlease use the bank transfer instructions provided by our team and send the transfer confirmation once completed.',true),
('PAYMENT_INSTRUCTIONS','so','Tilmaamaha lacag-bixinta','Salaan {{customer_name}},\n\nCodsiga safarkaaga ALHARAMAIN ELITE {{booking_id}} wuxuu diyaar u yahay lacag-bixin. Qiimaha guud waa {{currency}} {{total_amount}}.\n\nFadlan isticmaal xogta bangiga ee kooxdayadu ku siisay, kadibna noo soo dir caddeynta wareejinta.',true),
('PAYMENT_INSTRUCTIONS','ar','تعليمات الدفع','مرحبًا {{customer_name}}،\n\nطلب رحلتكم لدى ALHARAMAIN ELITE رقم {{booking_id}} جاهز للدفع. إجمالي قيمة الرحلة هو {{currency}} {{total_amount}}.\n\nيرجى استخدام بيانات التحويل البنكي التي أرسلها لكم فريقنا، ثم إرسال إشعار التحويل بعد إتمامه.',true),
('PAYMENT_RECEIVED','en','Payment received','Hello {{customer_name}},\n\nWe confirm that your payment for booking {{booking_id}} has been received and verified.\n\nOur team will continue preparing your journey and will share the next details with you.',true),
('PAYMENT_RECEIVED','so','Lacag-bixinta waa la xaqiijiyay','Salaan {{customer_name}},\n\nWaxaan xaqiijinay in lacag-bixinta booking-gaaga {{booking_id}} la helay oo la hubiyay.\n\nKooxdayadu waxay sii wadi doontaa diyaarinta safarkaaga waxayna kula wadaagi doontaa faahfaahinta xigta.',true),
('PAYMENT_RECEIVED','ar','تم استلام الدفع','مرحبًا {{customer_name}}،\n\nنؤكد لكم أنه تم استلام والتحقق من دفعة الحجز رقم {{booking_id}}.\n\nسيواصل فريقنا تجهيز رحلتكم وسنشارككم التفاصيل التالية تباعًا.',true),
('BOOKING_CONFIRMED','en','Booking confirmed','Hello {{customer_name}},\n\nYour ALHARAMAIN ELITE booking {{booking_id}} is confirmed for {{travel_period}}.\n\nGuests: {{guest_count}}\nPackage: {{package_name}}\n\nWe look forward to welcoming you.',true),
('BOOKING_CONFIRMED','so','Booking-ga waa la xaqiijiyay','Salaan {{customer_name}},\n\nBooking-gaaga ALHARAMAIN ELITE {{booking_id}} waa la xaqiijiyay. Taariikhda/muddada safarka: {{travel_period}}.\n\nMartida: {{guest_count}}\nXirmada: {{package_name}}\n\nWaxaan ku faraxsanahay inaan ku soo dhaweyno.',true),
('BOOKING_CONFIRMED','ar','تم تأكيد الحجز','مرحبًا {{customer_name}}،\n\nتم تأكيد حجزكم لدى ALHARAMAIN ELITE رقم {{booking_id}} للفترة {{travel_period}}.\n\nعدد الضيوف: {{guest_count}}\nالباقة: {{package_name}}\n\nيسعدنا استقبالكم.',true),
('PAYMENT_REMINDER','en','Payment reminder','Hello {{customer_name}},\n\nThis is a friendly reminder regarding the payment for your ALHARAMAIN ELITE booking {{booking_id}}. Please contact our team if you need any assistance.',true),
('PAYMENT_REMINDER','so','Xusuusin lacag-bixin','Salaan {{customer_name}},\n\nTani waa xusuusin ku saabsan lacag-bixinta booking-gaaga ALHARAMAIN ELITE {{booking_id}}. Fadlan nala soo xiriir haddii aad u baahan tahay caawimaad.',true),
('PAYMENT_REMINDER','ar','تذكير بالدفع','مرحبًا {{customer_name}}،\n\nهذه رسالة تذكير بخصوص دفعة حجزكم لدى ALHARAMAIN ELITE رقم {{booking_id}}. تواصلوا مع فريقنا إذا احتجتم إلى أي مساعدة.',true),
('TRAVEL_DETAILS','en','Journey details','Hello {{customer_name}},\n\nHere are your current ALHARAMAIN ELITE journey details:\nBooking: {{booking_id}}\nPackage: {{package_name}}\nTravel period: {{travel_period}}\nGuests: {{guest_count}}\n\nOur team remains available to support you.',true),
('TRAVEL_DETAILS','so','Faahfaahinta safarka','Salaan {{customer_name}},\n\nKuwani waa faahfaahinta safarkaaga ALHARAMAIN ELITE:\nBooking: {{booking_id}}\nXirmada: {{package_name}}\nMuddada safarka: {{travel_period}}\nMartida: {{guest_count}}\n\nKooxdayadu mar walba way kuu diyaar tahay.',true),
('TRAVEL_DETAILS','ar','تفاصيل الرحلة','مرحبًا {{customer_name}}،\n\nهذه هي تفاصيل رحلتكم الحالية لدى ALHARAMAIN ELITE:\nرقم الحجز: {{booking_id}}\nالباقة: {{package_name}}\nفترة السفر: {{travel_period}}\nعدد الضيوف: {{guest_count}}\n\nفريقنا متاح دائمًا لدعمكم.',true),
('HOTEL_DETAILS','en','Hotel details','Hello {{customer_name}},\n\nYour hotel arrangements for booking {{booking_id}} are being prepared by our operations team. We will share the confirmed hotel details with you as soon as they are finalized.',true),
('HOTEL_DETAILS','so','Faahfaahinta hoteelka','Salaan {{customer_name}},\n\nDiyaarinta hoteellada booking-gaaga {{booking_id}} waxaa gacanta ku haya kooxda hawlgallada. Waxaan kula wadaagi doonaa faahfaahinta la xaqiijiyay marka la dhammeeyo.',true),
('HOTEL_DETAILS','ar','تفاصيل الفندق','مرحبًا {{customer_name}}،\n\nيعمل فريق العمليات حاليًا على تجهيز ترتيبات الفنادق لحجزكم {{booking_id}}. سنشارككم تفاصيل الفنادق المؤكدة فور اعتمادها.',true),
('AIRPORT_TRANSFER','en','Airport transfer','Hello {{customer_name}},\n\nYour airport transfer arrangements for booking {{booking_id}} are being coordinated by our operations team. We will send the confirmed pickup details before your journey.',true),
('AIRPORT_TRANSFER','so','Gaadiidka garoonka','Salaan {{customer_name}},\n\nKooxdayada hawlgallada waxay diyaarinaysaa gaadiidka garoonka ee booking-ga {{booking_id}}. Waxaan kuu soo diri doonaa faahfaahinta qaadista ka hor safarka.',true),
('AIRPORT_TRANSFER','ar','تنسيق الاستقبال من المطار','مرحبًا {{customer_name}}،\n\nيقوم فريق العمليات بتنسيق خدمة الاستقبال من المطار لحجزكم {{booking_id}}. سنرسل لكم تفاصيل الاستقبال المؤكدة قبل الرحلة.',true),
('PRE_TRAVEL_REMINDER','en','Before your journey','Hello {{customer_name}},\n\nYour ALHARAMAIN ELITE journey is approaching. Please keep your travel documents ready and stay in touch with our team for the final arrangements for booking {{booking_id}}.',true),
('PRE_TRAVEL_REMINDER','so','Xusuusin ka hor safarka','Salaan {{customer_name}},\n\nSafarkaaga ALHARAMAIN ELITE wuu soo dhowaanayaa. Fadlan diyaari dukumentiyada safarka oo la soco kooxdayada si loo dhammeystiro diyaarinta booking-ga {{booking_id}}.',true),
('PRE_TRAVEL_REMINDER','ar','تذكير قبل السفر','مرحبًا {{customer_name}}،\n\nاقترب موعد رحلتكم مع ALHARAMAIN ELITE. يرجى تجهيز وثائق السفر والبقاء على تواصل مع فريقنا لاستكمال الترتيبات النهائية للحجز {{booking_id}}.',true),
('POST_JOURNEY_REVIEW','en','Thank you for travelling with us','Hello {{customer_name}},\n\nThank you for travelling with ALHARAMAIN ELITE. We would be grateful if you shared your verified experience with us after completing your journey.',true),
('POST_JOURNEY_REVIEW','so','Waad ku mahadsan tahay safarka','Salaan {{customer_name}},\n\nWaad ku mahadsan tahay safarka aad la qaadatay ALHARAMAIN ELITE. Waxaan jeclaan lahayn inaad nala wadaagto khibraddaada la xaqiijin karo kadib marka safarkaagu dhammaado.',true),
('POST_JOURNEY_REVIEW','ar','شكرًا لاختياركم لنا','مرحبًا {{customer_name}}،\n\nشكرًا لسفarkiinna مع ALHARAMAIN ELITE. يسعدنا أن تشاركونا تجربتكم الموثقة بعد إتمام الرحلة.',true)
) as v(key,language,subject,body,active)
on conflict (key, language) do update set subject=excluded.subject, body=excluded.body, active=true;